### ISSUE TITLE
TODOS keeps spinning forever (hangs)

### ISSUE THREAD

**Issue by pieter-groeneweg** [nextcloud/activity#100]
### Steps to reproduce
1. Create a task with an end date / create a calendar item with a reminder set
2. Select Activity, click Todos
3. ....

### Expected behaviour
I expect to see my list of todos

### Actual behaviour
The sperm keeps spinning forever, nothing happens

### Server configuration
Operating system**: Debian Jessie on a Raspberry Pi3

Web server: Apache 2.4.10

Database: MySQL 5.5.53

PHP version: PHP 7.0

Nextcloud version: 11.0.0

Where did you install Nextcloud from: download from site manually updated from 10

Signing status: No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.4.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

**The content of config/config.php:**

{
    "system": {
        "instanceid": "oc7u46gvlrvw",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "share.domain.com"
        ],
        "datadirectory": "\/home\/share\/public_html\/data",
        "overwrite.cli.url": "https:\/\/share.domain.com",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "share",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Amsterdam",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "no-reply",
        "mail_smtpmode": "smtp",
        "mail_domain": "domain.com",
        "maintenance": false,
        "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v0",
        "appstoreenabled": true,
        "appstore.experimental.enabled": true,
        "theme": "",
        "loglevel": 0,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_smtphost": "mail.domain.com",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "20"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.4.1",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.5.2",
            "ocsid": "168708",
            "signed": "true",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1477640435.9688",
            "lastcron": "1483652883",
            "lastupdateResult": "[]",
            "lastupdatedat": "1483652294",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "repairlegacystoragesdone": "yes",
            "updater.secret.created": "1481730901",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.6.1",
            "types": "filesystem"
        },
        "files_accesscontrol": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.2",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "16.0.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "levels": "10001",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "logging"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "prevent_group_restriction"
        },
        "richdocuments": {
            "doc_format": "odf",
            "enabled": "no",
            "installed_version": "1.1.14",
            "ocsid": "174727",
            "types": "",
            "wopi_url": "https:\/\/office.domain.com"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.1.3",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.4",
            "ocsid": "164356",
            "types": ""
        },
        "theming": {
            "backgroundMime": "image\/jpeg",
            "cachebuster": "5",
            "color": "#94dc28",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "logoMime": "image\/svg+xml",
            "name": "Share",
            "types": "logging",
            "url": "https:\/\/share.domain.com"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "updatenotification": {
            "calendar": "1.4.1",
            "contacts": "1.5.1",
            "core": "9.1.2.2",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "tasks": "0.9.4",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        }
    }
}

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
Browser: Chrome, Firefox

**Operating system: Windows 10

#### Nextcloud log (data/nextcloud.log)
about the last hour..

{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APCu not available for local cache","level":1,"time":"2017-01-05T23:03:02+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache","level":1,"time":"2017-01-05T23:03:02+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OCA\\Files_Trashbin\\BackgroundJob\\ExpireTrash job with ID 1","level":0,"time":"2017-01-05T23:03:02+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OCA\\Files_Trashbin\\BackgroundJob\\ExpireTrash job with ID 1","level":0,"time":"2017-01-05T23:03:02+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OCA\\UpdateNotification\\Notification\\BackgroundJob job with ID 4","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OCA\\UpdateNotification\\Notification\\BackgroundJob job with ID 4","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OCA\\Files_Versions\\BackgroundJob\\ExpireVersions job with ID 5","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OCA\\Files_Versions\\BackgroundJob\\ExpireVersions job with ID 5","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OCA\\Files\\BackgroundJob\\ScanFiles job with ID 6","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OCA\\Files\\BackgroundJob\\ScanFiles job with ID 6","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OCA\\Files\\BackgroundJob\\DeleteOrphanedItems job with ID 7","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"DeleteOrphanedItems","message":"0 orphaned system tag relations deleted","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"DeleteOrphanedItems","message":"0 orphaned user tag relations deleted","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"DeleteOrphanedItems","message":"0 orphaned comments deleted","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"DeleteOrphanedItems","message":"0 orphaned comment read marks deleted","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OCA\\Files\\BackgroundJob\\DeleteOrphanedItems job with ID 7","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OCA\\Files\\BackgroundJob\\CleanupFileLocks job with ID 8","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OCA\\Files\\BackgroundJob\\CleanupFileLocks job with ID 8","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OCA\\Activity\\BackgroundJob\\EmailNotification job with ID 10","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OCA\\Activity\\BackgroundJob\\EmailNotification job with ID 10","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OCA\\Activity\\BackgroundJob\\ExpireActivities job with ID 11","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OCA\\Activity\\BackgroundJob\\ExpireActivities job with ID 11","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OCA\\Files_Sharing\\DeleteOrphanedSharesJob job with ID 12","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OCA\\Files_Sharing\\DeleteOrphanedSharesJob job with ID 12","level":0,"time":"2017-01-05T23:03:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OCA\\Files_Sharing\\ExpireSharesJob job with ID 13","level":0,"time":"2017-01-05T23:03:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OCA\\Files_Sharing\\ExpireSharesJob job with ID 13","level":0,"time":"2017-01-05T23:03:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 14","level":0,"time":"2017-01-05T23:03:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"no app in context","message":"Invalidating session tokens older than 2017-01-04T22:03:04+00:00","level":0,"time":"2017-01-05T23:03:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"no app in context","message":"Invalidating remembered session tokens older than 2016-12-21T22:03:04+00:00","level":0,"time":"2017-01-05T23:03:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 14","level":0,"time":"2017-01-05T23:03:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OCA\\Federation\\SyncJob job with ID 2","level":0,"time":"2017-01-05T23:03:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OCA\\Federation\\SyncJob job with ID 2","level":0,"time":"2017-01-05T23:03:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OCA\\UpdateNotification\\ResetTokenBackgroundJob job with ID 17","level":0,"time":"2017-01-05T23:03:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OCA\\UpdateNotification\\ResetTokenBackgroundJob job with ID 17","level":0,"time":"2017-01-05T23:03:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OCA\\DAV\\CardDAV\\SyncJob job with ID 19","level":0,"time":"2017-01-05T23:03:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OCA\\DAV\\CardDAV\\SyncJob job with ID 19","level":0,"time":"2017-01-05T23:03:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Run OCA\\NextcloudAnnouncements\\Cron\\Crawler job with ID 20","level":0,"time":"2017-01-05T23:03:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"6R2ToV2HFAnALe0wlCYr","remoteAddr":"","app":"cron","message":"Finished OCA\\NextcloudAnnouncements\\Cron\\Crawler job with ID 20","level":0,"time":"2017-01-05T23:03:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}

If you happen to notice anything else ;)

**Comment by nickvergessen** [comment]
Already fixed with https://github.com/nextcloud/server/pull/2625/files

**Comment by pieter-groeneweg** [comment]
mmh the spinner stopped but it doesn't show any of my scheduled tasks or calendar items with or/without reminder. Am I missing something here?

**Comment by nickvergessen** [comment]
It shows when you add a new task or change an existing one, not a list of open tasks (that is what the task app does).

**Comment by pieter-groeneweg** [comment]
No it does not show anything.
If I create a new task with a due date, or change an existing task (due date, percentage done, ...) nothing shows in the TODOS activity.

**Comment by pieter-groeneweg** [comment]
Now that works. I can see my new-edited tasks in Activity todos.
Plse note in the first https://github.com/nextcloud/server/pull/2625/files it is mentioned to change `todo´ in ´todos´ in just one file in the second (the one that works) it is the other way around in two files (I assume as I do not have 'test")
Please be aware so correct ones end up in the next update. Tx

**Comment by nickvergessen** [comment]
yeah basically there are 3 files that need the same string. https://github.com/nextcloud/server/pull/2625 changed it from todo (2) todos (1) to todo (1) todos (2). And https://github.com/nextcloud/server/issues/3009 changed all 3 to the same usage.

**Comment by pieter-groeneweg** [comment]
but I don't have this apps/dav/tests/unit/CalDAV/Activity/Filter/TodoTest.php....

**Comment by nickvergessen** [comment]
Yeah, you can ignore that file

**Comment by nickvergessen** [comment]
The 3rd file is https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/Activity/Backend.php#L393
