### ISSUE TITLE
Move shows up wrongly in activity stream: You moved xx.pdf to xx.pdf

### ISSUE THREAD

**Issue by chaos-prevails** [nextcloud/activity#105]
### Steps to reproduce
1. move a file or folder with NC11 move function
2. click on activity stream
3. activity stream shows moved file/folder as destination instead of real destination folder

### Expected behaviour
the real destination folder should be displayed

### Actual behaviour
the moved file/folder name is displayed

### Server configuration
**Operating system**:
Ubuntu 16.04 64bit
**Web server:**
apache 2.4.6.
**Database:**
mariadb - stock Ubuntu 16.04
**PHP version:**
7.0.8

**Nextcloud version:** (see Nextcloud admin page)
11.0.0.10
**Where did you install Nextcloud from:**
download from nextcloud homepage

**Signing status:**
"no errors have been found"

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - announcementcenter: 3.0.0
  - comments: 1.1.0
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_clipboard: 0.5.0
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_automatedtagging
  - files_external
  - files_retention
  - notes
  - spreed
  - templateeditor
  - user_external
  - user_saml

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => 'X',
  'passwordsalt' => 'X',
  'secret' => 'X',
  'trusted_domains' =>
  array (
    0 => 'X',
  ),
  'datadirectory' => '/var/XX',
  'overwrite.cli.url' => 'X',
  'dbtype' => 'mysql',
  'version' => '11.0.0.10',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'X',
  'dbpassword' => ':X',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'iX',
  'mail_domain' => 'X',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'X' ,
  'mail_smtpauth' => 1,
  'mail_smtpport' => '465',
  'mail_smtpname' => 'X',
  'mail_smtppassword' => 'X',
  'mail_smtpsecure' => 'ssl',
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'remember_login_cookie_lifetime' => 60,
  'session_lifetime' => 60,
  'session_keepalive' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => true,
  'redis' =>
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
  'appstore.experimental.enabled' => true,
);
~                                       

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP (AD Windows Server 2012 R2)

### Client configuration
**Browser:**
Firefox 50, chromium (stock version Ubuntu 14.04)

**Operating system:**
Ubuntu 14.04 64bit
#### Nextcloud log (data/nextcloud.log)
nothing during testing

#### Browser log

Screenshot:
![move_wrong_activity](https://cloud.githubusercontent.com/assets/17159225/21890156/ace71a1e-d8cc-11e6-9203-99035464b44f.jpg)

**Comment by nickvergessen** [comment]
Right, the short message (hiding of the path in the tooltip) makes those messages a bit useless.

**Comment by chaos-prevails** [comment]
thanks!
are there any plans (NC12?) to be able to move/copy multiple files/folders at once (eg functionality on the horizontal top menu bar with download and delete)? Moving is already great but moving multiple files and copying multiple files would give the webinterface standard file explorer functionality.

Another (small) remark: if you move or copy something, often you want to end up where you moved the files/folders. Right now you stay where you are moving/copying from. Without disturbing the workflow and adding another checkbox, e.g.: after moving, a short information text shows up for a couple of seconds, like "you copied/moved xxx to <destination/folder/>". The <destination/folder/> is clickable and on clicking, the destination folder opens.

**Comment by nickvergessen** [comment]
Sorry, I have no idea about the moving functionality.

**Comment by chaos-prevails** [comment]
OK, I will look whether this feature request is already somewhere. If not, I will add it :)
I currently use files_clipboard in NC11 as a replacement.
