### ISSUE TITLE
Make it possible to sort certain activities and count the total

### ISSUE THREAD

**Issue by enoch85** [nextcloud/activity#107]
It would be nice to see how many times a certain publicly shared link is downloaded and it would be even cooler to be able to sort that into date, month and week.

Therefore I suggest to make it possible to see the total amount of downloads for a specific share. This could be shown as a tooltip or something like that.

Suggestions are welcome.

**Comment by nickvergessen** [comment]
Sorry, but that is not what this app is for. If you want a download counter, one should write a dedicated app for that.
