### ISSUE TITLE
[BITV] 9.1.3.1b/5.2 - The lists of activities under the "h2" headings like "Today" or "Yesterday" are not marked as lists using appropriate HTML mark-up (or ARIA equivalent). (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/activity#1101]
- [ ] Fix
- [ ] Backport

![10f77923cb7d08486f77f7636ccda404](https://user-images.githubusercontent.com/1315170/221933950-bd0e347e-02c6-4121-a3fb-043c94218868.png)

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1d5eadb58d-v5-n2

</details>

**Comment by nickvergessen** [comment]
This was already done with #1071

**Comment by nickvergessen** [comment]
But was only backported for 25.0.4 with https://github.com/nextcloud/activity/pull/1078

**Comment by AndyScherzinger** [comment]
Thanks a lot @nickvergessen 🙏
