### ISSUE TITLE
[BITV] 9.2.4.7/5.1 - Links with symbols receive a keyboard focus, but it is not well recognizable as the contrast ratio between the background and focus frame is less than 3:1. (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/activity#1102]
- [ ] Fix
- [ ] Backport

<img width="286" alt="596ccd4012133da9f30d8cb35ee74615" src="https://user-images.githubusercontent.com/1315170/222542376-78ea90d2-2e9e-4749-8f96-87b7f4214e22.png">

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-91f2646afa-v5-n1

</details>

**Comment by JuliaKirschenheuter** [comment]
contrast of focused link is enough

**Comment by JuliaKirschenheuter** [comment]
but contrast of focused link (text) is not enough:

![Screenshot from 2023-07-19 15-09-10](https://github.com/nextcloud/activity/assets/6078378/6e276b8c-ffc5-41d3-8df2-5e70b7b1d5c5)

![Screenshot from 2023-07-19 15-08-27](https://github.com/nextcloud/activity/assets/6078378/00f59f6f-28dc-46ea-b121-a5866ddae9f6)
