### ISSUE TITLE
Loading spinner should show vertically centered like in other apps

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/activity#111]
Currently the loading spinner is shown on towards the top of the #app-content. However it should be like in Mail, Files, and the other apps where it’s vertically centered.

cc @nextcloud/designers

**Comment by Rehan52004** [comment]
I want to work on it, please assign to me.

**Comment by jancborchardt** [comment]
@Rehan52004 if you like to work on it you can just go ahead, no need to be assigned. :)

**Comment by jancborchardt** [comment]
Actually, looking at the placement in the current version it seems fine, so closing this issue. :)
