### ISSUE TITLE
Problem with the widget

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/activity#1136]
### Steps to reproduce
When the dashboard is open on a tab and we switch to another tab then back to the widget bug

### Expected behaviour
That the widget does not bug and that the inscription "More Activities" are translated

### Actual behaviour
[https://imgur.com/a/R3umrSd](https://imgur.com/a/R3umrSd)

### Server configuration

**Operating system**: Debian 11 (docker)

**Web server:** (Apache 2)

**Database:** MYSQL

**PHP version:** 8.1

**Nextcloud version:** (see Nextcloud admin page) 26 but 25 are also good

**Where did you install Nextcloud from:** manual (docker)

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Chrome 100

**Operating system:** Windows 11 but 10 are also ok

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
jn @ globals.js:59
get @ globals.js:90
(anonymous) @ listener.js?v=7f0b99d4-105:152
removeChild @ vue.runtime.esm.js:6310
u @ vue.runtime.esm.js:6496
x @ vue.runtime.esm.js:6755
w @ vue.runtime.esm.js:6715
(anonymous) @ vue.runtime.esm.js:6839
B @ vue.runtime.esm.js:6909
Gi.nodeOps @ vue.runtime.esm.js:7077
t._update @ vue.runtime.esm.js:3769
r @ vue.runtime.esm.js:3875
t.get @ vue.runtime.esm.js:3446
t.run @ vue.runtime.esm.js:3522
wr @ vue.runtime.esm.js:4121
(anonymous) @ vue.runtime.esm.js:3143
Bn @ vue.runtime.esm.js:3065
Promise.then (async)
Cn @ vue.runtime.esm.js:3090
Nn @ vue.runtime.esm.js:3155
xr @ vue.runtime.esm.js:4207
t.update @ vue.runtime.esm.js:3513
t.notify @ vue.runtime.esm.js:720
set @ vue.runtime.esm.js:963
Wr.Zr.set @ vue.runtime.esm.js:5356
(anonymous) @ Dashboard.vue:96
c @ Dashboard.vue:45
(anonymous) @ Dashboard.vue:45
(anonymous) @ Dashboard.vue:45
Ve @ Dashboard.vue:45
a @ Dashboard.vue:86
Promise.then (async)
Ve @ Dashboard.vue:45
a @ Dashboard.vue:86
(anonymous) @ Dashboard.vue:86
(anonymous) @ Dashboard.vue:86
getActivities @ Dashboard.vue:86
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
jn @ globals.js:59
get @ globals.js:90
(anonymous) @ listener.js?v=7f0b99d4-105:152
removeChild @ vue.runtime.esm.js:6310
u @ vue.runtime.esm.js:6496
n @ vue.runtime.esm.js:6486
x @ vue.runtime.esm.js:6751
w @ vue.runtime.esm.js:6715
(anonymous) @ vue.runtime.esm.js:6839
B @ vue.runtime.esm.js:6909
Gi.nodeOps @ vue.runtime.esm.js:7077
t._update @ vue.runtime.esm.js:3769
r @ vue.runtime.esm.js:3875
t.get @ vue.runtime.esm.js:3446
t.run @ vue.runtime.esm.js:3522
wr @ vue.runtime.esm.js:4121
(anonymous) @ vue.runtime.esm.js:3143
Bn @ vue.runtime.esm.js:3065
Promise.then (async)
Cn @ vue.runtime.esm.js:3090
Nn @ vue.runtime.esm.js:3155
xr @ vue.runtime.esm.js:4207
t.update @ vue.runtime.esm.js:3513
t.notify @ vue.runtime.esm.js:720
set @ vue.runtime.esm.js:963
Wr.Zr.set @ vue.runtime.esm.js:5356
(anonymous) @ Dashboard.vue:92
c @ Dashboard.vue:45
(anonymous) @ Dashboard.vue:45
(anonymous) @ Dashboard.vue:45
Ve @ Dashboard.vue:45
a @ Dashboard.vue:86
(anonymous) @ Dashboard.vue:86
(anonymous) @ Dashboard.vue:86
getActivities @ Dashboard.vue:86
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
jn @ globals.js:59
get @ globals.js:90
(anonymous) @ listener.js?v=7f0b99d4-105:152
removeChild @ vue.runtime.esm.js:6310
u @ vue.runtime.esm.js:6496
n @ vue.runtime.esm.js:6486
x @ vue.runtime.esm.js:6751
w @ vue.runtime.esm.js:6715
(anonymous) @ vue.runtime.esm.js:6839
B @ vue.runtime.esm.js:6909
Gi.nodeOps @ vue.runtime.esm.js:7077
t._update @ vue.runtime.esm.js:3769
r @ vue.runtime.esm.js:3875
t.get @ vue.runtime.esm.js:3446
t.run @ vue.runtime.esm.js:3522
wr @ vue.runtime.esm.js:4121
(anonymous) @ vue.runtime.esm.js:3143
Bn @ vue.runtime.esm.js:3065
Promise.then (async)
Cn @ vue.runtime.esm.js:3090
Nn @ vue.runtime.esm.js:3155
xr @ vue.runtime.esm.js:4207
t.update @ vue.runtime.esm.js:3513
t.notify @ vue.runtime.esm.js:720
set @ vue.runtime.esm.js:963
Wr.Zr.set @ vue.runtime.esm.js:5356
(anonymous) @ Dashboard.vue:92
c @ Dashboard.vue:45
(anonymous) @ Dashboard.vue:45
(anonymous) @ Dashboard.vue:45
Ve @ Dashboard.vue:45
a @ Dashboard.vue:86
(anonymous) @ Dashboard.vue:86
(anonymous) @ Dashboard.vue:86
getActivities @ Dashboard.vue:86
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by susnux** [comment]
Should be with with https://github.com/nextcloud/activity/pull/1284
