### ISSUE TITLE
Recent Activity dashboard widget shows old activity and does not update

### ISSUE THREAD

**Issue by kz26** [nextcloud/activity#1137]
### Steps to reproduce
1. Login to Nextcloud
2. Go to Dashboard
3. Look at (or first enable) the Recent Activity widget

### Expected behaviour
Recent Activity should be appropriately updated with current activity

### Actual behaviour
Recent Activity instead shows activity from 4 months ago and does not appear to ever update with current activity

![image](https://user-images.githubusercontent.com/1066494/228015928-9fd31982-0593-4695-8f73-e41b7d94af1e.png)

### Server configuration

Docker Nextcloud-25.0.4-fpm

**Operating system**: Docker (Debian Bullseye)

**Web server:** nginx

**Database:** MariaDB 10.11.2 (Docker)

**PHP version:** PHP 8.1 (bundled with Docker)

**Nextcloud version:** 25.0.4

**Where did you install Nextcloud from:** Docker Hub

**Signing status:** No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - cloud_federation_api: 1.8.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - circles: 22.1.0
  - comments: 1.15.0
  - contactsinteraction: 1.2.0
  - encryption
  - federation: 1.11.0
  - files_external
  - photos: 1.4.0
  - suspicious_login
  - systemtags: 1.11.0
  - twofactor_totp
  - user_ldap
  - user_status: 1.1.1

**Nextcloud configuration:**

{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.mydomain.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.4.1",
        "overwrite.cli.url": "https:\/\/nextcloud.mydomain.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "theme": "",
        "trashbin_retention_obligation": "auto, 30"
    }
}

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Microsoft Edge 111.0.1661.54 (Official build) (64-bit) 

**Operating system:** Windows 10 Pro x64

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

N/A

#### Browser log
```

No browser network errors

**Comment by nickvergessen** [comment]
Please note that **own** activity will not be shown in the dashboard.
So the list should match `index.php/apps/activity/?filter=by`

**Comment by nickvergessen** [comment]
There is a way, but no intention to change that or add a user option for it

**Comment by kz26** [comment]
No problem. Just wanted to make sure this wasn't a bug of some sort :)
