### ISSUE TITLE
Provide tags

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/activity#1147]
For https://github.com/nextcloud/files-clients/issues/39 it is needed to have tags within activity stream.
Jan wished to have this only on Desktop, but other clients then also shall implement it.

From API side adding "tags": "['tag 1', 'tag 2'] might be the easiest, without breaking anything?

@AndyScherzinger for planning
@artonge @miaulalala for actual work

**Comment by nickvergessen** [comment]
I recommend to add a flag to the request to opt-in into this, also that might have quite some bad performance impact if done incorrectly. Should definitely only be populated in post-processing stage, so we can load all tags of all file ids with a single request.

**Comment by nickvergessen** [comment]
Since it's then used by official clients, it should be documented in https://github.com/nextcloud/activity/blob/master/docs/endpoint-v2.md#parameters as well

**Comment by tobiasKaminsky** [comment]
@nextcloud/designers 
can you provide us with ideas/mockup how tags should be shown?
For one file it is quite obvious, I think.
But what about clustered activities, e.g. "Tobias" has changed test.md, image.jpg and readme.md?

**Comment by tobiasKaminsky** [comment]
![image](https://user-images.githubusercontent.com/5836855/231715007-e93d950a-b1ff-4492-886c-09cb21319352.png)

**Comment by nimishavijay** [comment]
I would agree with Tobi, if one file was changed, show tags also
Tobias has added tags **Personal** and **Urgent** to **file.md**

If multiple files were changed:
Tobias has added tags to **file.md**, **test.md** and **review.md**

Additionally if it is possible to find out if the same tags were added to multiple files then they could be shown together
Tobias has added tags **Personal** and **Urgent** to **file.md**, **test.md** and **review.md**

**Comment by nickvergessen** [comment]
The question was not about when tags are assigned/removed, but how to show combined activity:

User A changed files 1, 2, 3


1 is tagged with 1A, 1B and 1C
2 is tagged with 2A, 2B and 2C
3 is tagged with 3A, 3B and 3C

We can not put those 9 tags in a single subline without giving indication which item is being referred to

**Comment by nimishavijay** [comment]
Right, in that case we can say "User A has added tags to files 1, 2, and 3" like I mentioned.

And in case 1, 2, and 3 are all tagged with the same tags A and B, "User A has added tags A and B to 1, 2, and 3" but this is a nice-to-have.

**Comment by nickvergessen** [comment]
It's not about the tagging action, it's about show the tags of files that were created/modified.

**Comment by nimishavijay** [comment]
Yes, I understand, I mean we don't have to show the individual tags if there are multiple files, like Tobi mentioned. 
I think I am misunderstanding something. Maybe @jancborchardt will understand this issue better?

**Comment by jancborchardt** [comment]
> I recommend to add a flag to the request to opt-in into this, also that might have quite some bad performance impact if done incorrectly.

If there is any performance concern with this then maybe it makes more sense to not do it in Activity (i.e. the desktop tray menu) but only in the details view (which is only one click away)?

So we do have the tags in file listings (like mobile apps and web view) but since the desktop app is an activity list, it does not need it.

**Comment by tobiasKaminsky** [comment]
From my side it is not about performance, but about how to show tags in case of multiple files.
Please check above discussion, starting there https://github.com/nextcloud/activity/issues/1147#issuecomment-1506631565

**Comment by AndyScherzinger** [comment]
I simply wouldn't show tags for activities on files/folders except if a file/folder got tagged, then show that as an activity. I don't think it adds extra value to the activity feed. Just my opinion.

**Comment by tobiasKaminsky** [comment]
@jancborchardt please clarify, as this was your idea/wish :-)

**Comment by jancborchardt** [comment]
Yep, after thinking about it more, considering possinle designs and drawbacks I have to agree with @AndyScherzinger.

And as I said above, resoning:

> So we do have the tags in file listings (like mobile apps and web view) but since the desktop app is an activity list, it does not need it.

Of course for activities which are for tagging / removing tags, those should show in the stream.

**Comment by tobiasKaminsky** [comment]
This is already the case:
![image](https://user-images.githubusercontent.com/5836855/232771951-db7929a0-3804-436a-aefb-ed0ec0d27a09.png)

So nothing to do :)
