### ISSUE TITLE
`Activity Settings` button does not open settings menu

### ISSUE THREAD

**Issue by Fenn-CS** [nextcloud/activity#1199]
### Steps to reproduce
1. Install, configure and activate activities app
2. Open settings app from dashboard and click on "Activity Settings" (Check bottom left)

### Expected behaviour
Should open activity settings menu

### Actual behaviour
Does nothing

**Operating system**: Ubuntu 22

**Web server:** Apache2

**Database:** PostgresSQL

**PHP version:** PHP 8.0.28

**Nextcloud version:** Nextcloud Hub 5 (28.0.0 dev)

**Comment by Sachin24704** [comment]
Hey, please assign me this issue...

**Comment by Fenn-CS** [comment]
@Sachin24704 Do you have time to work on this anytime soon? 

It would be nice to have this before looking at this : https://github.com/nextcloud/activity/issues/1110 

We would be happy to assign you something else if you don't have time to work on this around now (next few days)....

**Comment by szaimen** [comment]
Backport to 27 is missing
