### ISSUE TITLE
Truncate more than 5 files to “and others”

### ISSUE THREAD

**Issue by jGleitz** [nextcloud/activity#121]
(This is not really a bug report, so I’m not using the template).

In older versions of own-/Nextcloud, if there was an activity with more than 5 affected files, the first 5 files where listeted in the message and the others were truncated to „and others“. But there was only ever one entry for consecutive activities of the same type.

In Version 11.0.2 of Nextcloud, the behaviour is different: Entries only show a maximum of 5 files. If a certain activity happens for `n` files, there will be `ceil(n / 5)` entries in the activity view.

I don’t know if the behaviour was changed on purpose, and if yes, why. However, I liked the “and others”-option a lot more. In our context, we often have a lot of files created or modified at once. With the old option, the activity view was a lot cleaner than it is now.

If the new behaviour was introduced on purpose, it would be awesome to have a setting for this.

**Comment by nickvergessen** [comment]
Explanation is in the other issue. Sorry if it bothers you 😞

**Comment by jGleitz** [comment]
For reference for others, from [nextcloud/files_downloadactivity#12](https://github.com/nextcloud/files_downloadactivity/pull/12) by @nickvergessen :

> Yeah, it's a code design decision in the servers code:
https://github.com/nextcloud/server/blob/da9468522b9e846d10b6e91ad10fa0c1b3b99546/lib/private/Activity/EventMerger.php#L225-L226
> 
>I dropped the "others"-tooltip, because otherwise we would have needed another API endpoint for the desktop and mobile clients, since they can't use tooltips like we do.

Sorry to hear that this will not be implemented, although I understand the reason. Thanks for explaining!
