### ISSUE TITLE
[feature request] give admin ability to turn off e-mail notifications

### ISSUE THREAD

**Issue by KB7777** [nextcloud/activity#122]
If admin doesn't want to set e-mails to users and there is no e-mail settings at server it will be super to give ability to turn off e-mail notifications, so the users couldn't set it.

**Comment by nickvergessen** [comment]
And why should the admin do that?

**Comment by KB7777** [comment]
Our buisness gives to users synchronization only. We want to reduce confusions of our users, because we don't want to support any e-mails. We want to give them as little funkcionality as possible -- synchronization only :) 

Yes, we can disable the app, but the app is very usefull, but e-mails are unnecessery at our point of implementetion.
