### ISSUE TITLE
Feature Request: integation with Notifications app

### ISSUE THREAD

**Issue by rakshazi** [nextcloud/activity#123]
### Expected behaviour
Activity app adds notifications about new activities in notifications app

### Actual behaviour
Activity app doesn't add notifications about new activities in notifications app

**Comment by nickvergessen** [comment]
Notifications are way to noice, they are send to your desktop and phone in the feature.
So no way we are going to add an additional notification for each file change, etc.

**Comment by rakshazi** [comment]
But it's just one case. For my case we need this notifications, because we use nextcloud for caldav and carddav features. Why you don't want to give ability for your users to have this feature?

**Comment by nickvergessen** [comment]
What kind of caldav/carddav action would you want a notification for?

**Comment by rakshazi** [comment]
Notifications about new events and contacts.
Can you implement this, please?
The best way is give users to choose which notifications they want to receive in Personal section
