### ISSUE TITLE
Activity said: "Unable to load the activity list" in Details side panel 

### ISSUE THREAD

**Issue by zapikp** [nextcloud/activity#1283]
Activity in Details side panel show:
![image](https://github.com/nextcloud/activity/assets/56720963/46c58427-9cf8-41df-b490-38fe1b5ba70d)
but global Activity list show events normally:
![image](https://github.com/nextcloud/activity/assets/56720963/444e1b3f-57ac-493a-a0cb-97b50c46fa7d)

### Steps to reproduce
1. Open files tab and click Details, Activity

### Expected behaviour
Show activity evenst for selected files and folders.

### Actual behaviour
Show error "Unable to load the activity list"

### Server configuration

**Operating system**:
Debian 12, but same behavior I can see on Debian 12

**Web server:**
Apache2 2.4.57-2

**Database:**
MariaDB 10.5.19
**PHP version:**
8.2.7-1

**Nextcloud version:** (see Nextcloud admin page)
27.0.2, but the same behavior I can see on versions 25.0.xx

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**
www-data@srvnextcloud:~/nextcloud$ php occ app:list
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - bruteforcesettings: 2.7.0
  - encryption: 2.15.0
  - files_external: 1.19.0
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
www-data@srvnextcloud:~/nextcloud$ php occ config:list system
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.litovel.eu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.0.2.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "CZ",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "app_install_overwrite": [
            "ldapcontacts"
        ],
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Google Chrome 115.0.5790.170

**Operating system:**
Debian  12

#### Nextcloud log (data/nextcloud.log)
```

Inse{"reqId":"jOOE6CStbD1e3LrmSE0v","level":1,"time":"2023-08-17T07:48:12+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::startCheckCodeIn
{"reqId":"jOOE6CStbD1e3LrmSE0v","level":1,"time":"2023-08-17T07:48:14+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::finishedCheckCod
{"reqId":"jOOE6CStbD1e3LrmSE0v","level":1,"time":"2023-08-17T07:48:14+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Updat
{"reqId":"jOOE6CStbD1e3LrmSE0v","level":1,"time":"2023-08-17T07:48:14+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceDisab
{"reqId":"jOOE6CStbD1e3LrmSE0v","level":1,"time":"2023-08-17T07:48:14+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Rrt your Nextcloud log here
```

**Comment by MP715** [comment]
Same issue here.

**Comment by elhossary** [comment]
Same issue here

**Comment by zapikp** [comment]
Solved for me. 
problem was in reverse proxy on FortiGate. Test behind the proxy is OK!
