### ISSUE TITLE
Request : no notify_email_shared=1 by default

### ISSUE THREAD

**Issue by adrienfr44** [nextcloud/activity#131]
After fresh install of nextcloud 11.0.2, after i desactivated/activated Activity App, there's no entry in database (table oc_preferences) by default.  However, **notification mail concerning"A file or folder has been shared" is  activated/checked by default ** for all users in their "Personnal" panels.

For a user User1, in his "Personnal" panel, if i uncheck this (notification mail concerning "A file or folder has been shared"), i see in database (table oc_preferences) lot of records and specially one:

- userid : User1
- appid : activity
- configkey    :  notify_email_shared
- configvalue :  0 

Question : 
- Why notify_email_shared  is equivalent 1 by default (when there isn't entry in database)? 
- Is it possible to modify that or to give the possibility of setting the default values ​​in Administrator panel.

ps: the same about "A file or folder was shared from another server" (no notify_email_remote_share=1 by default)

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Apache

**Database:**
mysql 

**PHP version:**
php5

**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**Comment by nickvergessen** [comment]
I think it's time to integrate https://github.com/mfleonhardt/activitydefaults into the normal activity app.

**Comment by nickvergessen** [comment]
@mfleonhardt you want to come up with a PR? Or shall I take care of it?
