### ISSUE TITLE
Can't limit app usage to certain groups

### ISSUE THREAD

**Issue by Notespeak** [nextcloud/activity#140]
### Steps to reproduce
1. 
2.
3.

### Expected behaviour
An ability to exclude the app usage right from certain user groups.

### Actual behaviour
All users can use the app.

### Server configuration

**Operating system**:
linux ubuntu 16.04
**Web server:**
apache
**Database:**
mysql
**PHP version:**
7.x

**Nextcloud version:* 11.02* (see Nextcloud admin page) 
**Where did you install Nextcloud from:** 
Web

**Signing status:**
No errors have been found.
```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**
activity: 2.4.1
activitylog: 0.0.1
admin_audit: 1.1.0
comments: 1.1.0
contacts: 1.5.3
dav: 1.1.1
deck: 0.1.2
direct_menu: 0.10.1
external: 1.2
federatedfilesharing: 1.1.1
federation: 1.1.1
files: 1.6.1
files_accesscontrol: 1.1.2
files_downloadactivity: 1.0.1
files_external: 1.1.2
files_markdown: 1.0.1
files_pdfviewer: 1.0.1
files_retention: 1.0.1
files_sharing: 1.1.1
files_texteditor: 2.2
files_trashbin: 1.1.0
files_versions: 1.4.0
files_videoplayer: 1.0.0
firstrunwizard: 2.0
gallery: 16.0.0
logreader: 2.0.0
lookup_server_connector: 1.0.0
nextcloud_announcements: 1.0
notes: 2.2.0
notifications: 1.0.1
password_policy: 1.1.0
provisioning_api: 1.1.0
qownnotesapi: 17.3.0
serverinfo: 1.1.1
sharebymail: 1.0.1
survey_client: 0.1.5
systemtags: 1.1.3
templateeditor: 0.2
theming: 1.1.1
twofactor_backupcodes: 1.0.0
updatenotification: 1.1.1
workflowengine: 1.1.1
Disabled:
calendar.2
encryption
files_automatedtagging
nexttant
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
"system": {
"datadirectory": "/home/***/nextcloud_***",
"dbtype": "mysql",
"version": "11.0.2.7",
"installedat": "1334086349.5631",
"lastupdatedat": "1334087083.9888",
"dbname": "***",
"dbhost": "**,
"dbtableprefix": "oc",
"dbuser": "REMOVED SENSITIVE VALUE",
"dbpassword": "REMOVED SENSITIVE VALUE",
"installed": true

"theme": "",
"maintenance": false,
"loglevel": 3,
"trusted_domains": [
"owncloud.***.ch",
"www.***.ch",
"***.ch"
],
"mail_from_address": '",
"mail_smtpmode": "php",
"mail_domain": "***.ch",
"secret": "REMOVED SENSITIVE VALUE",
"trashbin_retention_obligation": "auto, auto",
"appstore.experimental.enabled": true,
"memcache.local": "\OC\Memcache\APCu",
"updater.release.channel": "stable
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
This was answered multiple times already.
This is not possible atm, because when the app is not loaded for a user, you wouldn't see actions those users perform as well, leaving you with a non-complete activity log which is not what you would expect. This is due to the nature of how the "limit app to group" works at nextcloud.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/issues/3707#issuecomment-284385742
