### ISSUE TITLE
Switching to *By you* loads for page of data, then stalls without any error

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/activity#1410]
### Steps to reproduce
1. Open `/apps/activity/all`
2. Click *By you*

### Expected behaviour

All data loads

### Actual behaviour

First page loads and a spinner shows

![Bildschirmfoto vom 2023-11-13 10-33-27](https://github.com/nextcloud/activity/assets/1374172/6ef9d4bd-5a44-4888-a71d-4b6846f81cb3)

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 28.0.0 beta 2

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

cc @susnux

**Comment by susnux** [comment]
I can not reproduce this, neither on master nor on Nextcloud 28 beta 2.
Did this happen every time for you? Could you please check if there is an error in the browser console? Or check the requests section of the browsers dev tools for any failed request?

**Comment by ChristophWurst** [comment]
It does work for me today :shrug: 

There were no errors in the console AFAIR.

**Comment by susnux** [comment]
Closing it then as I still can not reproduce, please reopen if you encounter it again.
