### ISSUE TITLE
Sidebar stream sharing icon is cropped

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/activity#1417]
### Steps to reproduce
1. Open the sidebar of a file that was shared

### Expected behaviour

Icon is fully visible

### Actual behaviour

Icon is cropped slightly

![image](https://github.com/nextcloud/activity/assets/1374172/3c629e48-dbe8-4a6f-b946-64b0e646d27b)

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 28

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by ChristophWurst** [comment]
related to https://github.com/nextcloud/activity/pull/1388 @susnux or did you PR only change the main view, not the Files sidebar?

**Comment by susnux** [comment]
@ChristophWurst No I only migrated the app view not the sidebar

**Comment by nickvergessen** [comment]
Even worse on dark mode:
![grafik](https://github.com/nextcloud/activity/assets/213943/74c1b0be-34e1-4a9e-8c74-9b8d66fc51e7)


There is a background all of a sudden hiding all the images

**Comment by nickvergessen** [comment]
The unset from https://github.com/nextcloud/activity/pull/1416/files#diff-c36ebc18734fe5785adebd61a09d027225436bccce081743b938b0f7ca53913dL286-L288 was dropped instead of moved. Will send a patch
