### ISSUE TITLE
[feature request] making http requests/API calls for Activities

### ISSUE THREAD

**Issue by devRV** [nextcloud/activity#146]
Is it possible to implement the possibility NextCloud to make http requests or API calls when activities are occurring and sending the activity details as a json string?

**Comment by nickvergessen** [comment]
Not really, but you can read the RSS feed, if that is okay for you.
Or you use the API directly when you want json.

**Comment by ibr123** [comment]
if I made an application that behaves similar to activities **(listens to files activities through web hooks)** can I still send these activities as an http post request to a certain API? meaning can I send http requests from the NextCloud server?
keep in mind that this app is not activity app

Thanks

**Comment by nickvergessen** [comment]
You can write your own app, which listens to the same hooks as the activity app does and then run whatever code you like
