### ISSUE TITLE
Icons of selected entries in navigation are not inverted according to background highlight

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/activity#1462]
### Steps to reproduce
1. Open the Activity app
2. Look at the left navigation and its icons

### Expected behaviour
Icons of selected entry are white / inverted.

### Actual behaviour
Text is properly inverted / white, icons stay black. Possibly a component issue? @marcoambrosini @szaimen maybe something to look into?
![image](https://github.com/nextcloud/activity/assets/925062/2774946e-25df-4d8f-bb4d-3489b44eaf59)

### Server configuration

Current setup on cloud.nc as well as on tech-preview

**Comment by szaimen** [comment]
> Possibly a component issue? 

Yes, looks like it.

@marcoambrosini @szaimen maybe something to look into?

I fear I cannot look into it today. Going to vacation tomorrow.
