### ISSUE TITLE
ActivityTab fails to load: undefined `error` var reference in JS catch statement

### ISSUE THREAD

**Issue by ndl** [nextcloud/activity#1494]
### Steps to reproduce

Open 'Info' sidebar in 'Memories' app while in a folder and select 'Activity' tab. Should likely be reproducable in other scenarios as well, see e.g. #1283 which looks very similar.

### Expected behaviour

Should display the normal activity tab with a possibility to write a message and see the list of past activities.

### Actual behaviour

Shows  empty tab with just a text "Unable to load the activity list".

JS console shows an exception ActivityTab JS file [at the following line](https://github.com/nextcloud/activity/blob/master/src/views/ActivityTab.vue#L159).

### Fix

The experession `error.response !== undefined && error.response.status === 304` on that line should read `e.response !== undefined && e.response.status === 304`. I've verified that with this change the activity tab works fine.

**Comment by MP715** [comment]
> ### Steps to reproduce
> Open 'Info' sidebar in 'Memories' app while in a folder and select 'Activity' tab. Should likely be reproducable in other scenarios as well, see e.g. #1283 which looks very similar.
> 
> ### Expected behaviour
> Should display the normal activity tab with a possibility to write a message and see the list of past activities.
> 
> ### Actual behaviour
> Shows empty tab with just a text "Unable to load the activity list".
> 
> JS console shows an exception ActivityTab JS file [at the following line](https://github.com/nextcloud/activity/blob/master/src/views/ActivityTab.vue#L159).
> 
> ### Fix
> The experession `error.response !== undefined && error.response.status === 304` on that line should read `e.response !== undefined && e.response.status === 304`. I've verified that with this change the activity tab works fine.

How and where do I make this change?
