### ISSUE TITLE
Activity does not load (blank screen) although dashboard widget loads

### ISSUE THREAD

**Issue by tobykurien** [nextcloud/activity#1535]
### Steps to reproduce
1. Upgrade/install Nextcloud Hub 7 28.0.1
2. Access "Activity"

### Expected behaviour
Activity should load

### Actual behaviour
Activity does not load, shows a blank screen. The javascript console shows this error: Loading module from “https://[server]/apps/activity/js/activity-app.mjs?v=753a16f7-3” was blocked because of a disallowed MIME type (“text/plain”)..  This was replicated on 3 different instances.

### Server configuration

**Operating system**: Rocky Linux

**Web server:** thttpd and PHP-FPM

**Database:** mysqld  Ver 10.11.5-MariaDB for Linux on x86_64

**PHP version:** 8.1

**Nextcloud version:** (see Nextcloud admin page) Nextcloud Hub 7 (28.0.1)

**Where did you install Nextcloud from:** Downloaded tarball from nextcloud.com

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
  - activity: 2.20.0                                                                                                           
  - bruteforcesettings: 2.8.0                                                                                                  
  - calendar: 4.6.4                                                                                                            
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0         
  - comments: 1.18.0                                           
  - contacts: 5.5.1                                            
  - contactsinteraction: 1.9.0                                 
  - dashboard: 7.8.0                                           
  - dav: 1.29.1      
  - deck: 1.12.1                                                                                                               
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - fileslibreofficeedit: 1.1.0 
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mail: 3.5.5
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.2
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - ransomware_protection: 1.14.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.1
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - tables: 0.6.6
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
```

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Linux

#### Nextcloud log (data/nextcloud.log)

No errors in the log when accessing Activity

```

```

#### Browser log
```
Loading module from “https://[server]/apps/activity/js/activity-app.mjs?v=753a16f7-3” was blocked because of a disallowed MIME type (“text/plain”).
JQMIGRATE: Migrate is installed, version 3.4.1
Content-Security-Policy: The page’s settings blocked the loading of a resource at https://[server]/apps/viewer/js/viewer-components.js?v=ada191fba38f09fe10b7 (“default-src”).
```

**Comment by tobykurien** [comment]
After posting this, I think I see the problem: the .mjs extension needs to be set as content type "application/javascript", I'm guessing.

**Comment by tobykurien** [comment]
Confirmed, issue is content type header for .mjs files.

**Comment by regs01** [comment]
Updated to 28.0.3 it's still blank

**Comment by nickvergessen** [comment]
No, I'm no longer the maintainer of this app.

**Comment by joshtrichards** [comment]
This is not a bug. It's a misconfiguration, as noted by the original reporter. Please see the *Critical Changes* section of the v28 Release Notes for `.mjs` file handling + updated web server configs: https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_28.html#web-server-configuration
