### ISSUE TITLE
 Missing my name and avatar in both stream and email

### ISSUE THREAD

**Issue by oparoz** [nextcloud/activity#155]
```
Today at 11:51 AM
changed Press/Reading/.....pdf
```

### Server configuration

**Nextcloud version:** 12rc1

**Comment by nickvergessen** [comment]
Well the "funny" thing is, that for changes you did yourself, there is no name used:
https://github.com/nextcloud/server/blob/master/apps/files/lib/Activity/Provider.php#L153-L155

**Comment by oparoz** [comment]
Thank you @nickvergessen for identifying the cause:
https://github.com/nextcloud/richdocuments/issues/28
