### ISSUE TITLE
teams icon in the left sidebar has wrong color

### ISSUE THREAD

**Issue by szaimen** [nextcloud/activity#1594]
Just tested on nc29.0.0b1

The teams icon in the left sidebar has the wrong color:
![image](https://github.com/nextcloud/activity/assets/42591237/84191557-4785-4e1e-94d5-c8943be38810)

**Comment by AndyScherzinger** [comment]
Same on light theme on RC1, just inverted

<img width="239" alt="2024-04-03 20_51_56-Activity - Nextcloud – Mozilla Firefox" src="https://github.com/nextcloud/activity/assets/1315170/3de20f60-5050-4c78-bac8-043e193d24e4">

can you align on this one @sorbaugh to have this fixed before the final 29.0.0?
