### ISSUE TITLE
Avatar/information missing when file gets edited via public link

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/activity#161]
### Steps to reproduce
1. Share a file via a public link and make it editable
2. Let an anonymous user edit the file (e.g. via collabora online)
3. Browse File change activity

### Expected behaviour
Maybe show "Someone has changed $file"

### Actual behaviour

Missing avatar is shown

![2017-05-24-111919_959x266_scrot](https://cloud.githubusercontent.com/assets/3404133/26396238/e7ac4f9e-4072-11e7-8b49-2f619d966ade.png)

**Comment by nickvergessen** [comment]
Already fixed on master, backport is awaiting review:
https://github.com/nextcloud/server/pull/5063

Feel free to +1 it
