### ISSUE TITLE
Add execution time for notification creation on setting "daily"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/activity#162]
Each user has notification settings.
Please add a time option if setting "Send emails" is set to "Daily".
Benefit: You can set time e.g. to 6 AM and every user has his notification summary of the last day when he check emails in the morning.

Have seen this feature at products like [Wrike](http://wrike.com/) and [Alfresco](https://www.alfresco.com/) and it really helps staying productive.

Already filed same issue on ownCloud repo some time ago. See https://github.com/owncloud/activity/issues/385

**Comment by rakekniven** [comment]
As @nickvergessen already mentioned in older issue there is the need to add timezone as user setting.
Should I file a separate issue or wait? What do @karlitschek think of it?

**Comment by nickvergessen** [comment]
We added a feature for this in https://docs.nextcloud.com/server/12/admin_manual/configuration_server/activity_configuration.html#better-scheduling-of-activity-emails

This at least helps to deal with the issue, when all users are from about the same timezone.
Anything more is too complicated for now.

**Comment by rakekniven** [comment]
Sounds very promising. Oh, version 12. Will try it in some days after I brought myself to upgrade.

**Comment by nickvergessen** [comment]
Closing as per above
