### ISSUE TITLE
Provide the current path in the activities API

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/activity#166]
* create a file and a folder
* move the file into that folder
* update the file in that folder
* rename the folder

The API now shows the activity for the "update file" but it still links to the old path. Thus for example the Android app can't easily link to that file, because neither the path is correct (because the parent was renamed afterwards) nor is there an easy way to get the path of an file ID (webdav search doesn't support this yet - @icewind1991)

Would it be possible to add the "current path" of a file in an activity to an activity element? 

cc @nickvergessen 

For Android: @aleister09 @imjarp @mario @tobiasKaminsky

**Comment by nickvergessen** [comment]
Searching by file id is possible:
https://github.com/nextcloud/server/pull/4222

I would like to avoid the hundreds of queries on the database when viewing the activity stream and instead only do this when we actually need it. So would be nice if they could either use the search or look it up in their database, or doesn't the android app have a file id database like the desktop client?!

**Comment by tobiasKaminsky** [comment]
On android there is an internal file id database but it is only synced partially on demand.
So it could and will be that the informations on a file are outdated. Therefore we first refresh the data on every action (entering folder, ...).

**Comment by MorrisJobke** [comment]
Okay - then this way. 👍
