### ISSUE TITLE
Mimetype icons broken for deleted files

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/activity#167]
* create a folder
* mimetype icons are fine:
<img width="667" alt="bildschirmfoto 2017-06-15 um 23 21 28" src="https://user-images.githubusercontent.com/245432/27211814-8d5a1f56-5221-11e7-9078-a501d19992fe.png">

* delete this folder

* mimetype icons are broken (even for the old event of the creation):
<img width="711" alt="bildschirmfoto 2017-06-15 um 23 22 04" src="https://user-images.githubusercontent.com/245432/27211821-9b81d52e-5221-11e7-84b3-d99ea14f1f37.png">

cc @nickvergessen

**Comment by MorrisJobke** [comment]
cc @aleister09 for finding this

**Comment by nickvergessen** [comment]
This has always been the case, the problem is we dont store the types and by the name it could also be a file without a type...
Will have a look if I find an easy to implement idea for the delete. But fixing other activities of the same file will be a nightmare

**Comment by MorrisJobke** [comment]
Relabeled as enhancement.

**Comment by MorrisJobke** [comment]
@nickvergessen But you have the file ID, right? And this file ID still exists, because the file is in the trashbin. Couldn't you read that information from there?

**Comment by nickvergessen** [comment]
Trashbin should still show it. Only if that is disabled or you delete it completely the info is not there anymore...
