### ISSUE TITLE
Clarification on icon handling for events

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/activity#169]
There seems to be an issue with SVG images in the [activity emails on gmail](https://github.com/nextcloud/server/issues/5075).
IIRC @nextcloud/ios also had issues with SVG, correct?

If so I would go ahead and add a flag to the activity manager, which indicates whether SVG (android and web) or PNG (ios and email) should be used. Then the providers can check the flag before setting the icon.

Other options are:
1. Always PNG (might appear blurry here and there)
2. NC endpoint which returns a PNG while taking a SVG path as a parameter (would require Imagick)
3. Be hated

cc @MorrisJobke @LukasReschke opinions?

**Comment by LukasReschke** [comment]
> If so I would go ahead and add a flag to the activity manager, which indicates whether SVG (android and web) or PNG (ios and email) should be used. Then the providers can check the flag before setting the icon.

LGTM

**Comment by MorrisJobke** [comment]
Yep - the flag makes sense 👍
