### ISSUE TITLE
Make Calendar activity entries interactive

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/activity#170]
Currently an activity entry looks like this:

> **Jos Poortvliet** created event **Berlin Meetup** in calendar **Nextcloud**

Of that, only the username is interactive, showing the contact popover as it should. :) Clicking the event name and calendar name should also be interactive though:

- Event name: open the calendar app in a new tab, with the event scrolled in focus and sidebar for the event open
- Calendar name: just open the calendar app

What do you think @nickvergessen @georgehrke @raghunayyar @tcitworld?

**Comment by nickvergessen** [comment]
Yeah there is an issue in the calendar app already. So far it has no links that would allow this.
And then this has to be implemented in the dav app since that is the provider of the events

**Comment by tcitworld** [comment]
Link to https://github.com/nextcloud/calendar/issues/21 for future ref.
