### ISSUE TITLE
List of available types

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/activity#172]
Is there a list of available types?

I only found this:

<img width="788" alt="bildschirmfoto 2017-06-20 um 13 17 48" src="https://user-images.githubusercontent.com/245432/27348935-4fed9df8-55bb-11e7-9e3e-8ca6de391ed3.png">
<img width="402" alt="bildschirmfoto 2017-06-20 um 13 19 24" src="https://user-images.githubusercontent.com/245432/27348936-500afb64-55bb-11e7-8304-0fdfa1f47a7a.png">
<img width="386" alt="bildschirmfoto 2017-06-20 um 13 21 47" src="https://user-images.githubusercontent.com/245432/27348977-6dff2640-55bb-11e7-909c-4fa017481d6a.png">

@imjarp asked for this.

@nickvergessen Could we compile a list of available types even if they are from different apps provided, just to get an overview.

**Comment by nickvergessen** [comment]
what for? I guess it makes more sense to have an api for the settings?

**Comment by MorrisJobke** [comment]
Seems that the API provides everything ... so the type should not be interpret.

**Comment by MorrisJobke** [comment]
Is this only for filtering then?

**Comment by MorrisJobke** [comment]
> what for? I guess it makes more sense to have an api for the settings?

Settings is the filter?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/activity/blob/master/docs/filter.md#filter-apps
Yeah filters work based on apps and types (and there is a hack for the favorite filter).
But maybe we should publish the filters via an api, that would make sense for the mobile apps.

**Comment by MorrisJobke** [comment]
The question behind this is: What action should be executed on Android? What to do for example with the email change activity? How can we port this to the mobile apps? Because currently it only provides a link for the action. Should that link be parsed somehow?

That is the background of this question.

cc @mario @AndyScherzinger @tobiasKaminsky

**Comment by nickvergessen** [comment]
Activities dont have an action

> What to do for example with the email change activity?

Just display the activities?! Like with all other activities? It is an information for the user, not necessarily interactive

**Comment by imjarp** [comment]
Currently in the android client, the "files activities" redirect to the file o directory , and i agree with @nickvergessen not all activities are necessarily interactive, but we want to know if there is an easy way to distinguish

**Comment by nickvergessen** [comment]
Well just make non-file activities "not clickable" it's still valuable information for the user.
If there is no entry in link, dont make it clickable, if there is, you can click it and follow the link
