### ISSUE TITLE
[stable29 only]: Comments attached to the wrong file if details sidebar left open

### ISSUE THREAD

**Issue by carpediem-av** [nextcloud/activity#1772]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I discovered the following bug in Nextcloud v28.0.1. Steps to reproduce the bug:
1. Open the Activities tab for the PDF file and leave a comment.
2. Without closing the Activities tab, close the PDF viewer.
3. Open another PDF file from the same folder and try to leave a comment.
The comment is not left, but is included in the list of comments in the first file.
This bug already existed before in older versions (approximately in versions 17-20), and now you have introduced it again. This is very sad, my users wrote dozens of comments to the wrong files, all the work was ruined.

### Steps to reproduce

1. Open the Activities tab for the PDF file and leave a comment.
2. Without closing the Activities tab, close the PDF viewer.
3. Open another PDF file from the same folder and try to leave a comment.
The comment is not left, but is included in the list of comments in the first file.

### Expected behavior

The comment should have been left on the second file

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Fixed in #1771
