### ISSUE TITLE
Command option to limit the number of emails send.

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/activity#179]
An `-n` option could limit the number of emails sent through `activity:send-mails` by overriding `MailQueueHandler::CLI_EMAIL_BATCH_SIZE`.

**Comment by nickvergessen** [comment]
Are you running in a timeout, or why would you only notify an unknown set of users?

**Comment by tcitworld** [comment]
It's more like the 500 emails are being sent too fast and our mailq didn't felt well. Anyway, this constant feels quite arbitary.

**Comment by tcitworld** [comment]
It would be also nice to have this kind of setting when it's done through the cron call, but I don't really see how to offer such an option apart from an admin setting. Will open another issue if needed.
