### ISSUE TITLE
Dutch language wrong in file: activity/blob/master/l10n/nl.js 

### ISSUE THREAD

**Issue by JK74** [nextcloud/activity#191]
https://github.com/nextcloud/activity/blob/master/l10n/nl.js

the line:
"Choose for which activities you want to get an email notification, and which should show up in the activity app stream." : "Kies voor welke activiteiten **he** een e-mailnotificatie wenst en welke in de activiteiten app-stream moeten verschijnen.",

The bold word 'he' is wrong and should be 'je' 
thnx, jeroen

![image](https://user-images.githubusercontent.com/17946255/29614428-62bceb06-880a-11e7-9429-dbc4a37e680b.png)

**Comment by rullzer** [comment]
Fixed on transifex. should be synced tomorrow

**Comment by JK74** [comment]
thanks guys; I see indeed that transifex needs still a lot of Dutch translations and reviews. I'll see how I can contribute there although the layout is a bit fuzzy logic at this moment.
