### ISSUE TITLE
txt and md file previews in the Activity app are not displayed properly

### ISSUE THREAD

**Issue by sunjam** [nextcloud/activity#220]
Typography cuts off for some reason in text and markdown files being previewed in the current Activity app of Nextcloud 12.0.3.
![activity-info-displayed](https://user-images.githubusercontent.com/1787238/33518932-23a17ed6-d752-11e7-8b2c-3796c2c8f028.png)

**Comment by nickvergessen** [comment]
The activity app shows the thumbnails of the files,
That are also the same in the files app.

If those should be different it should be changed in the main repository
