### ISSUE TITLE
Notification Email

### ISSUE THREAD

**Issue by DarkknightAK** [nextcloud/activity#221]
In the activity notification mail you see the last 200 changes but when there were more than 200 file changes (someone upload a bulk of files) you geht the first 200 listed * and 334 more

it would be nice to configure how many files were listed.

**Comment by DarkknightAK** [comment]
this question was asked in the help forum some times

https://help.nextcloud.com/t/number-of-entries-in-email-notification/8957
https://help.nextcloud.com/t/notification-email/23748

**Comment by nickvergessen** [comment]
> it would be nice to configure how many files were listed.

The problem is that your server might run out of memory at some point, when parsing thousands of activities for hundreds of users in one go.

**Comment by ferdiga** [comment]
IMO it would be sufficient and more readable to notify "user committed 200 changes in file ...."

**Comment by DarkknightAK** [comment]
And when you get a link to the notification page and add there an export to ... action.

Or give the option to set an checkbox to review the documents.

**Comment by DarkknightAK** [comment]
I think this should work with the automated tagging function, where you can define that if an file was uploaded (to folder x by ... ) the file get the tag review needed and than it can be solved that way.
