### ISSUE TITLE
Remove activity log about shared items before sharing

### ISSUE THREAD

**Issue by ManOki** [nextcloud/activity#222]
### Steps to reproduce
1. Put a file inside a folder
2. Delete this file.
3. Share folder to others.

### Expected behaviour
The other one should not see information about the file in the activity log.

### Actual behaviour
The other one see that the file was created, deleted and afterwards, the folder was shared.

From my POV, there should also be no information in the activity log, if i temporarily revoke the share, do some changes and share again. On the other side old information (before revoking) should be available, if i share again.

**Comment by nickvergessen** [comment]
> there should also be no information in the activity log, if i temporarily revoke the share, do some changes and share again. On the other side old information (before revoking) should be available, if i share again.

That is exactly how it works.

I just tested this to check and it behaved exactly like that.

Actions that happen before a share and between revoke+reshare are not logged for other users.
