### ISSUE TITLE
Reset activity log

### ISSUE THREAD

**Issue by realies** [nextcloud/activity#225]
Would it be possible to introduce the ability to reset the activity log in general and per user?

**Comment by nickvergessen** [comment]
You can simply truncate the `oc_activity` database table.
Or you `DELETE FROM oc_activity WHERE affecteduser = '<user-id>'`

**Comment by realies** [comment]
It would be useful to see this within the UI elements.

**Comment by isdnfan** [comment]
removing activities is especially useful after you upload lot of files. in my case I found my fresh NC instance became really slow after uploading all my documents >40k files which logically resulted in thousands of activity notifications..

it would be useful to have auto-truncate after some time (it's only limited value to see activities after some weeks or months) and manual clean-up on demand..

**Comment by nickvergessen** [comment]
That should not make your instance slow in any way. We have millions of entries in the database and it's blasing fast.
Can you run the `occ db:add-missing-indices` command to see if something is missing from the installation?

**Comment by nickvergessen** [comment]
> it would be useful to have auto-truncate after some time (it's only limited value to see activities after some weeks or months) and manual clean-up on demand.

That's build in, default is 1 year. https://docs.nextcloud.com/server/19/admin_manual/configuration_server/activity_configuration.html#configuring-your-nextcloud-for-the-activity-app

**Comment by isdnfan** [comment]
> 
> 
> That should not make your instance slow in any way. We have millions of entries in the database and it's blasing fast.
> Can you run the `occ db:add-missing-indices` command to see if something is missing from the installation?

I ran the command but it looks everything is in place:

`Check indices of the share table.
Check indices of the filecache table.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Check indices of the calendarobjects_props table.
Check indices of the schedulingobjects table.
Check indices of the oc_properties table.
Done.`

I have to admit my hardware is not really powerful - this is docker running on a NAS (Celeron+8GB RAM) but it should be much more performant as Raspi, which is often used.
