### ISSUE TITLE
Activity Endpoint Error

### ISSUE THREAD

**Issue by ibr123** [nextcloud/activity#228]
Hi,

Thanks for sharing this app, the listening to the user activity is what I was looking for, I already installed the NextCloud Server on a server, and its working fine, and added the activity app on the server as well, also working fine, and the app is showing any activity that was made by the user, now as a test I wanted to get the activities that are described in this [link](https://github.com/nextcloud/activity/blob/master/docs/endpoint-v2.md)
Using postman I tried GET with **http://NextCloudServer/ocs/v2.php/apps/activity/api/v2/activity** but returned `server unavailable` , then typed the same URL at the browser and returned 

![untitled](https://user-images.githubusercontent.com/26926171/34478007-0025a5be-efa7-11e7-956b-51ea4b6bab30.png)

and the user was logged in.

Any idea that can help?

Thanks in advance

**Comment by nickvergessen** [comment]
`Server unavailable` sounds like a temporary issue, so just try again later.

Regarding the `CSRF check failed` that is on all ocs/* endpoints. You need to set the header `OCS-APIRequest: true`, then it should work fine.
