### ISSUE TITLE
Activity icon not shown in personal settings navigation if language set to German

### ISSUE THREAD

**Issue by schokonsti** [nextcloud/activity#238]
### Steps to reproduce
1. Set Language to German (_de_ or _de-DE_)
2. Visit _Personal Settings_ page (/settings/personal)

### Expected behaviour
There should be an activity icon in the navigation sidebar on the left. The HTML attributes mustn't be translated.
The code should look like this (refering to the right CSS class):
_Navigation:_
`<a href="#activity" class="nav-icon-activity">Aktivität<div></div></a>`
_Content:_
```
<div id="activity">
  <form id="activity_notifications" class="section">
    <h2>Aktivität</h2>
   [...]
  </form>
</div>
```

### Actual behaviour
The id and class names musn't be translated:
_Navigation:_
`<a href="#aktivität" class="nav-icon-aktivität">Aktivität<div></div></a>`
_Content:_
```
<div id="aktivity">
  <form id="activity_notifications" class="section">
    <h2>Aktivität</h2>
   [...]
  </form>
</div>
```

### Server configuration

**Operating system**: Linux 3.14.79-grsec-pvops-xen-x64 #1 SMP Mon May 22 13:12:26 CEST 2017 x86_64

**Web server:**  Apache/2.4.27 (cgi-fcgi)

**Database:** MySQL  5.6.19

**PHP version:** 7.0.20

**Nextcloud version:** 12.0.4.3

**Where did you install Nextcloud from:** Webinstaller

**Signing status:** No errors have been found.

**List of activated apps:**

_Enabled:_
**activity: 2.5.2**, bruteforcesettings: 1.0.3, calendar: 1.5.7, comments: 1.2.0, dav: 1.3.0, defaultgroup: 0.3.0, federatedfilesharing: 1.2.0, federation: 1.2.0, files: 1.7.2, files_pdfviewer: 1.1.1, files_sharing: 1.4.0, files_texteditor: 2.4.1, files_trashbin: 1.2.0, files_versions: 1.5.0, files_videoplayer: 1.1.0, firstrunwizard: 2.1, gallery: 17.0.0, groupfolders: 1.1.0, logreader: 2.0.0, lookup_server_connector: 1.0.0, music: 0.5.5, nextcloud_announcements: 1.1, notifications: 2.0.0, oauth2: 1.0.5, password_policy: 1.2.2, polls: 0.8.0, provisioning_api: 1.2.0, serverinfo: 1.2.0, sharebymail: 1.2.0, survey_client: 1.0.0, systemtags: 1.2.0, theming: 1.3.0, twofactor_backupcodes: 1.1.1, updatenotification: 1.2.0, workflowengine: 1.2.0
_Disabled:_
admin_audit, encryption, files_external, user_external, user_ldap

**Nextcloud configuration:**
**version:** 12.0.4.3

### Client configuration
**Browser:** Firefox 57.0.4, Chromium 63.0.3239.84

**Operating system:** Ubuntu 16.04.3 LTS

**Comment by nickvergessen** [comment]
Fixed in 13
