### ISSUE TITLE
Feature request: Send push notifications to mobile clients

### ISSUE THREAD

**Issue by awesome-manuel** [nextcloud/activity#268]
Since the [notifications app](https://github.com/nextcloud/notifications) supports push notifications to mobile clients, the activities could also be sent via this route. This might be more conventient than notification emails for a lot of users.

**Comment by nickvergessen** [comment]
Well notifications require interactions. We don't think it's a good idea to spam the user with push notifications to tell them a file was changed by someone.

**Comment by awesome-manuel** [comment]
And you think emails are less like spam? I mean the user could still configure what he wants to receive via push notification and maybe even how often.

**Comment by nickvergessen** [comment]
The problem is, push is very limited and strict. We can not combine 200 events like we do in one email atm.

**Comment by awesome-manuel** [comment]
Sure, but it's enough if the notification says "A lot of stuff changed" and you get to the activity stream by clicking on the notification.

**Comment by KunaPrime** [comment]
I just wanted to add, that some events as shared files are important to some people and notification would be useful. Sure spamming is not good for productivity but i would like to be in control of that (for myself or group that I am administering). 

Keep up the great work!!
