### ISSUE TITLE
Multiple same entries on activity log

### ISSUE THREAD

**Issue by nickcn** [nextcloud/activity#272]
### Steps to reproduce
1. Download a file via browser or sync via client
2. Open activity app

### Expected behaviour
Downloaded files appearing once

### Actual behaviour
Downloaded files appear multiple times

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache

**Database:** mysql

**PHP version:** 7.0.29

**Nextcloud version:** 13.0.2

*********************************
Hello,

I don't know if this is an issue or there is some problem with my config, but whenever I download or sync a file via the browser or the client respectfully, the log files seem to be written (?) twice or more times (I also have entries appearing four times for the same file). Is this the expected behavior?

I can provide any kind of logs or configs if needed.

Thanks in advance
*********************************

![browser](https://user-images.githubusercontent.com/6990195/40961066-2d55876c-68aa-11e8-8194-a2cb74281451.PNG)

**Comment by hartwinleen** [comment]
I can confirm the same behaviour. So if it is a configuration issue; we both have it :-)

**Comment by satellouk** [comment]
same here on a lubuntu 16.04 server

**Comment by paul-vp** [comment]
I noticed this issue (only) in the details-sidebar within the folders. It appears twice when the sidebar opens, but when switching to "comments" and back the double entries are gone.

Version 14.0.4 / PHP: 7.2.12
![activities_double_entry](https://user-images.githubusercontent.com/45493795/49442232-28374c80-f7c9-11e8-9151-32a60ebf0981.png)

**Comment by nickvergessen** [comment]
@paul-vp The issue in the sidebar was fixed for the next release of the Nextcloud server.

@nickcn I just packages a new release for the "files_downloadactivity" app which generates those. While testing the new version I could not reproduce this issue.

If it is still happening feel free to comment.
