### ISSUE TITLE
Request: Add object parent id

### ISSUE THREAD

**Issue by usselite** [nextcloud/activity#276]
The file sharing API exposes a "file_parent", handy if you want to track changes (download, upload) eventually to a certain folder. The activity API does not expose a object parent id or whatsoever. 

Can this be added to the model?

**Comment by nickvergessen** [comment]
And what should the parent be for files? and what for other objects?

**Comment by usselite** [comment]
Personally I think the parent (usually?) locates to a folder.

E.g. let's say we have these scenarios:
###1: User **uploads a document to the default 'Documents**' directory and shares the document. That specific document gets downloaded. The parent object id should now refer to the **'Documents' folder**.
###2: User **uploads a entire folder** to the root (creates folder, uploads file(s)), shares the folder. **Folder** gets downloaded again, parent object id should now refer to that newly created folder.
###3: User makes a public share available in the root directory, e.g. 'customer x upload'. That specific customer uploads files in that folder, parent object id should be 'customer x upload'.

I hope that makes sense. This would make keeping track of changes in a folder easier to follow.

**Comment by nickvergessen** [comment]
So basically you want to show the info of modified files in the parent folder?
See #45
