### ISSUE TITLE
Crash on android due to unshare a calendar

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/activity#277]
- share a calendar with a public link
- remove this link
- open up activity stream on android
- GSON parser fails at
```
{
"activity_id":2126,
"app":"dav",
"type":"calendar",
"user":"tobi",
"subject":"You removed public link for calendar ",
"subject_rich":
	["You removed public link for calendar {calendar}",
		{"actor":{"type":"user","id":null,"name":null},
		"calendar":"type":"calendar","id":3,"name":null}}],
"message":null,"message_rich":["",[]],"object_type":"calendar","object_id":3,"object_name":"","objects":{"3":""},"link":"","icon":"http:\/\/10.0.2.2\/nc13\/core\/img\/places\/calendar-dark.svg","datetime":"2018-06-18T13:58:03+00:00"}
```

actor.id is null and this makes it crash.

--> is this allowed to be null? (same for name) Then I will harden it…

**Comment by nickvergessen** [comment]
Is this on Master or 13?

**Comment by tobiasKaminsky** [comment]
I could only tried it on NC13, as with master I have no idea how to install calendar app / it looks very broken to me, if I clone it into /apps.
If you want me, I can try it again on master.

**Comment by tcitworld** [comment]
Probably introduced with https://github.com/nextcloud/server/pull/6590, but it seems other calendar activities could be affected too.

**Comment by tobiasKaminsky** [comment]
@nickvergessen I verified it with latest master and daily ~15.06. calendar app:
java.lang.IllegalStateException: Expected STRING but was NULL at path $[0].subject_rich[1].actor.id

Also happens when I add a public link.

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/server/pull/10078

Well no, it should not be null. But it would also be nice if the app doesnt break, when there is wrong data send :see_no_evil:

**Comment by tobiasKaminsky** [comment]
Thanks for the fix :+1: 

With https://github.com/nextcloud/android-library/pull/153 the app sets a value which cannot be read to empty string, so that at least all the other context of an activity is shown.
(the app itself never crashed on this, but it did not show any activity at all, although only one was failing)
