### ISSUE TITLE
Feature request - Log remote IP on events

### ISSUE THREAD

**Issue by FGIKCM** [nextcloud/activity#279]
Hello,

It could be great to log the remote IP on activities (mainly for accessed public files sharing and so). I know we can have this information on Apache access logs, but we do not have the name of the Nextcloud user sharing the file in this log, so it is not really useful.

This was partly asked in another issue: https://github.com/nextcloud/activity/issues/98

Best regards,

**Comment by nickvergessen** [comment]
Yeah, should be dealt with in https://github.com/nextcloud/activity/issues/98

Either we do it all or nothing.
