### ISSUE TITLE
[Feature request] Delete activity older than x days from database

### ISSUE THREAD

**Issue by Ich5003** [nextcloud/activity#281]
### Idea
I recently discoverd, that the activity app uses most space of my database as I have many file changes.
I'd love to see an option to automatically remove activities from the database older than for example 30 days or set a maximum of entries.

### Expected behaviour
Having a maximum limit of entries in the oc_activity database or delete them after a specific amount of time

### Actual behaviour
Database continues to grow and get's really big

**Comment by nickvergessen** [comment]
https://docs.nextcloud.com/server/12/admin_manual/configuration_server/activity_configuration.html#configuring-your-nextcloud-for-the-activity-app
