### ISSUE TITLE
Feature Request: More filters (Time-Range, User, Operation)

### ISSUE THREAD

**Issue by muckinger** [nextcloud/activity#288]
To better filter the very long Activity Log, we need to have more filters. Best would be additionally:

- Filter by a Time-Span (From-To)
- As Admin: Filter by a User
- Filter by Action (deleted, created, changed, renamed...)

Would  be great if this can be a new Feature. Didn't find a request for this.

Thx.

**Comment by ccoenen** [comment]
This is similar to #71. That ticket is already tagged, so I'll pile on there :-)

**Comment by nickvergessen** [comment]
Duplicate of #71
