### ISSUE TITLE
Filters don't work on 14

### ISSUE THREAD

**Issue by oparoz** [nextcloud/activity#292]
### Steps to reproduce

1. Click on "Von Ihnen"
2.
3.

### Expected behaviour

I should my activities only

### Actual behaviour

I see activities of other people.
There also seem to be a infinite loop somewhere which ends up crashing the tab.

**Comment by nickvergessen** [comment]
Problem is that the scroll container changed and therefor it things there is no hidden content until the bottom of the page and continues to load more.

Sadly I forgot about the issue, so this is 14.0.1 ¯\_(ツ)_/¯

**Comment by skjnldsv** [comment]
Strangely I cannot reproduce on my dev instance!
Only happening on c.nc.com
