### ISSUE TITLE
Notifications about my own actions

### ISSUE THREAD

**Issue by zelvik** [nextcloud/activity#294]
Notifications about my own actions are sending via email, but I didn`t set it.

### Steps to reproduce
1. Set this settings
<img width="665" alt="image" src="https://user-images.githubusercontent.com/7302263/45238118-079e4a00-b2e1-11e8-9a0d-3f929cf7e9ca.png">
2. Test notifications

### Expected behaviour
It should send notification about events created by other, not me

### Actual behaviour
Send email that I created. event

### Server configuration
**Operating system**:
Debian

**Web server:**
Apache

**Database:**
MariaDB
**PHP version:**
7.0.23
**Nextcloud version:** (see Nextcloud admin page)
13.0.6.1
**Where did you install Nextcloud from:**
oficial

**Comment by nickvergessen** [comment]
Those are the default settings for new users, not your own settings.
There should be another activity entry in the upper half of the settings

**Comment by zelvik** [comment]
Yes, but the problem is that I am receiving notification about created (or edited) events by me. And I have not got checked "Notify about your own actions via email".

**Comment by zelvik** [comment]
Yes, now it is working. I am sorry, I didn't know that there are two almost same settings :).
