### ISSUE TITLE
Folder icons do not change when theme color is changed

### ISSUE THREAD

**Issue by pautri** [nextcloud/activity#296]
### Steps to reproduce
1. Under "theming", change the color to something other than the default blue
2. Create a new folder
3. Go to the activity view

### Expected behaviour
Folder icons get the theme color that is specified

### Actual behaviour
Folders icons have the default blue color

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
14.0.0

**Comment by Ricain** [comment]
Same issue with NC 15.

**Comment by despens** [comment]
Same issue with NC 16.

**Comment by tobiasKaminsky** [comment]
![image](https://user-images.githubusercontent.com/5836855/58941219-99a58700-877b-11e9-8087-fb9f1dfc0c8f.png)

Same also for non-folder icons. In this case it is some kind of archive icon used.

**Comment by tobiasKaminsky** [comment]
@juliushaertl @skjnldsv maybe?

**Comment by juliushaertl** [comment]
Fix is in https://github.com/nextcloud/server/pull/15875

**Comment by tobiasKaminsky** [comment]
@juliushaertl what about other tinted mimetypes, like in above screenshot "archive"?
