### ISSUE TITLE
Bug report/Feature request: Circle links in mail reports

### ISSUE THREAD

**Issue by maliskovik** [nextcloud/activity#303]
Environment:
Nextcloud: 14.0.3
Activity:  2.7.0

Problem description:
Email notifications have broken links for circle activity.

Current behaviour: 
Circle names in email reports are relative links which when clicked in a mail client like Thunderbird - do nothing, and in web clients throw you to an non-existing page - relative to the web-mail client domain.

Expected behaviour:
Circle names  in email reports are links which should direct you to the circle page where you can accept invitation/confirm new member.

**Comment by nickvergessen** [comment]
This needs to be fixed in the circles app:
https://github.com/nextcloud/circles/pull/246/commits/5b786ceacb520e9a902f95731120f7ecb75b412e

**Comment by maliskovik** [comment]
Ah, I see. 
I wasn't  sure, which plugin handles the link generation, so I picked the most likely.
This fix was FAST though, well done :+1:
