### ISSUE TITLE
Database table seems broken after consecutive upgrades

### ISSUE THREAD

**Issue by Zibc** [nextcloud/activity#309]
### Steps to reproduce
1. enable activity app
2. find out some functionnalities are broken

### Expected behaviour
Functionnalities should not be broken

### Actual behaviour
unable to run occ db:convert-filecache-bigint: it throws an exception:
[Doctrine\DBAL\Schema\SchemaException]
There is no column with name ‘object_id’ on table ‘oc_activity’.
-> there is indeed no such column in the database table

unable to remove events from calendar because of the same reason
calendar throws error code 500 because of that every once in a while

the table looks like this:

    Name 	Type 	Collation 	Attributes 	Null 	Default 	Comments 	Extra
    1 	activity_idPrimary 	int(11) 			No 	None 		AUTO_INCREMENT
    2 	timestampIndex 	int(11) 			No 	0 		
    3 	priority 	int(11) 			No 	0 		
    4 	type 	varchar(255) 	utf8_bin 		Yes 	NULL 		
    5 	userIndex 	varchar(64) 	utf8_bin 		Yes 	NULL 		
    6 	affecteduserIndex 	varchar(64) 	utf8_bin 		No 	None 		
    7 	appIndex 	varchar(255) 	utf8_bin 		No 	None 		
    8 	subject 	varchar(255) 	utf8_bin 		No 	None 		
    9 	subjectparams 	varchar(255) 	utf8_bin 		No 	None 		
    10 	message 	varchar(255) 	utf8_bin 		Yes 	NULL 		
    11 	messageparams 	varchar(255) 	utf8_bin 		Yes 	NULL 		
    12 	file 	varchar(255) 	utf8_bin 		Yes 	NULL 		
    13 	link 	varchar(255) 	utf8_bin 		Yes 	NULL 		

### Server configuration

**Operating system**: debian 8

**Web server:** apache

**Database:** MySQL

**PHP version:** 5.6

**Nextcloud version:** 13

**Where did you install Nextcloud from:** upgrade from 12 on same server

**Signing status:**

**List of activated apps:**

**Nextcloud configuration:**

What should I do to fix the database ?

**Comment by nickvergessen** [comment]
Well this happened for some people if the app was disabled between nextcloud 9 and 10 or an earlier step I think.

but we can add a workaround to ensure the column is created

**Comment by Zibc** [comment]
That was quick!

Is there any chance to this fix coming also as a possible update for the current 13 and 14 versions of nextcloud ? I haven't updated to 14 yet, but I plan to do so.

I can also add manually the column is this fixes the issue, but with what properties ?

Thanks for quick reaction again guys!

**Comment by nickvergessen** [comment]
I will backport it to 14, so it will come with the next release of 14

**Comment by Zibc** [comment]
what about 13 ? although I know it will soon be in "end of life"
