### ISSUE TITLE
Unshare event is missing

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/activity#317]
* userA shares a file to userB
* userB unshare the file
* expected: userA & userB should see an "userB unshared file" event in the activity stream
* actual: there is none

This shows: admin shared and unshared and then admin shared and test unshared (last one is missing):

<img width="710" alt="bildschirmfoto 2018-11-22 um 21 15 27" src="https://user-images.githubusercontent.com/245432/48920932-408b9b00-ee9c-11e8-9496-782cbc3ec904.png">

cc @nickvergessen 

Might be related to https://github.com/nextcloud/server/issues/12062

**Comment by nickvergessen** [comment]
Also unshare for mail shares is missing, investigating
