### ISSUE TITLE
Feature Request: Show full path for new files in activity stream

### ISSUE THREAD

**Issue by k1ngf15h3r** [nextcloud/activity#332]
### Steps to reproduce
1. Activate activity stream for file creation
2. Create or upload a file in a specific location
3. Activity stream only shows the filename (full path only on mouseover)

### Expected behaviour
Abillity to configure activity stream to always show the full file path

### Actual behaviour
Only filename is shown 

### Server configuration

**Operating system**: Docker on CentOS

**Nextcloud version:** 15

**Where did you install Nextcloud from:** Docker Hub

**Comment by nickvergessen** [comment]
Our designer didn't like this back then, which is why the "removing of the path" was done in first place.

I'm also not going to add a config for something like this, so up to @nextcloud/designers if we change this or keep it as is.

**Comment by jancborchardt** [comment]
In practice this becomes really crowded when it’s part of the file name and it’s hard to see what the file name actually is. But yes, of course the tooltip only works on desktop and we need to make this work on mobile too.

We could show the folder path in a second row like so:
(If the file/folder is in the root/main folder, we would not show that row.)
![activity feed folder path](https://user-images.githubusercontent.com/925062/50869192-463d3180-13b3-11e9-94c6-bcc1daa3fa83.png)

What do you think?

**Comment by k1ngf15h3r** [comment]
This is perfect 👍🏻 Will this also be effecting the e-Mail Notification? This will be also helpful

**Comment by k1ngf15h3r** [comment]
Should is good 😅 at my last tests the did not with Version 15. is there maybe a config which handle this? My System is upgraded since version 11 so maybe there is something config related to change?

**Comment by nickvergessen** [comment]
Just tested and it works fine in emails:
> Today at 3:11 PM
You created test/subtext/Activity.vue

Also no configs involved.

**Comment by k1ngf15h3r** [comment]
Can confirm that this now works by our customer after upgrading to 15.0.1
