### ISSUE TITLE
Restore action has no icon

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/activity#341]
The restore action does not seem to have an icon – we should simply use the ➕ icon-add for it.
![bildschirmfoto von 2019-01-22 14-12-53](https://user-images.githubusercontent.com/213943/51537833-eda87280-1e4f-11e9-8b70-b411b922ee46.png)

**Comment by nickvergessen** [comment]
also the green one, or a monochrome one, so there is a difference?

**Comment by jancborchardt** [comment]
Actually even better would be `icon-history`: https://github.com/nextcloud/server/blob/master/core/img/actions/history.svg

That’s monochrome, and it’s also symmetric to the restore action from deleted files.
