### ISSUE TITLE
ID (OC:ID) only uniqueid but absent the instanceid

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/activity#344]
All the Nextcloud iOS is based on file ID or oc:id where this is a unique id + instance id, now this endpoint use only the (int) unique id and for the client this is a problem and is not coherent with other api.

@nickvergessen @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
the oc:id is instance id + unique id.
The later part is the same as the id used here.
As you know on which server/account you are, you can use this to either build your own oc:id or do it vice vera and use only file id without instance id.

**Comment by marinofaggiana** [comment]
id user ? my id user in User Profile is marinofaggiana ...

**Comment by nickvergessen** [comment]
If you come to the office today, we can talk about this directly and post the result here.
