### ISSUE TITLE
Activity icon preview with collabora is not displayed properly

### ISSUE THREAD

**Issue by Mysterycz** [nextcloud/activity#345]
### Steps to reproduce
1. Upload or create some of .doc or xls document
2. Share it for example as downloadable link and download it (from another account)
3. Check activity App, there is missing icon (only visible "Download file")

See attachment:
![shares](https://user-images.githubusercontent.com/20899532/52205966-1df10780-2879-11e9-95f3-4e96f35ec787.PNG)

There is link: /index.php/core/preview.png?file=/Test_activity_share.ods&x=150&y=150&c=503e1647cecd57306295044fa34843b2

If you delete this shared file, preview icon is fixed:
![share2](https://user-images.githubusercontent.com/20899532/52206046-50026980-2879-11e9-8713-b0293a2a137a.PNG)

There is link: /index.php/apps/files/?dir=/&scrollto=Test_activity_share.ods.d1549280091&view=trashbin

I am using latest NC 15.0.2 and latest Apps + latest collabora online app and core.

**Comment by nickvergessen** [comment]
Seems to be a problem with collabora then,
please report it there.
