### ISSUE TITLE
Shared videos count multiple times

### ISSUE THREAD

**Issue by TheNickSkater** [nextcloud/activity#352]
### Steps to reproduce
1. Share video with public link
2. Click on that link
3. Look at activitys

### Expected behaviour
Should show that it was watched once

### Actual behaviour
For me, it shows 3 times downloaded, even tough it was only 1 person clicking on the link

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:**Php7.2

**Nextcloud version:** Newest 15.0.5

**Where did you install Nextcloud from:** Official nextcloud page

List of activated apps: https://pastebin.com/KknLGgD4

Config: https://pastebin.com/dcf5TZGw

**Comment by jakobroehrl** [comment]
Problem still there on NC19

**Comment by t-franz** [comment]
Still having this problem on NC21.0.4 – streaming a video causes multiple download-messages:

![nextcloud-activity](https://user-images.githubusercontent.com/6214519/134530747-ec52263a-c43f-4b36-8b94-018e4d24b082.png)
