### ISSUE TITLE
Activity + mysql_4byte_support

### ISSUE THREAD

**Issue by docmcfly** [nextcloud/activity#367]
Hi, 

after the upgrade to nextcloud 15.07 I see a warning: You have not a 4 byte support for the emojis. I take the official tutorial: 

https://docs.nextcloud.com/server/15/admin_manual/configuration_database/mysql_4byte_support.html

But the last step generates a error message: 

In AbstractMySQLDriver.php line 115:
  An exception occurred while executing 'ALTER TABLE `activity` CO
  ARACTER SET utf8mb4 COLLATE utf8mb4_bin;':

  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size
   The maximum row size for the used table type, not counting BLOB
  . This includes storage overhead, check the manual. You have to
   columns to TEXT or BLOBs

In PDOStatement.php line 107:

  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size
   The maximum row size for the used table type, not counting BLOB
  . This includes storage overhead, check the manual. You have to
   columns to TEXT or BLOBs

In PDOStatement.php line 105:

  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size
   The maximum row size for the used table type, not counting BLOB
  . This includes storage overhead, check the manual. You have to
   columns to TEXT or BLOBs

My workaround was, i change the colmns  "subjectparams" and "messageparams" to text. 

i dont know, the activity app needs emojis support? 

thanks and regards
Clemens

**Comment by nickvergessen** [comment]
The problem is you had the app disabled on an update before. Use the following query to update the activity table to the latest version:
```sql
ALTER TABLE `oc_activity` CHANGE `app` `app` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL, CHANGE `subjectparams` `subjectparams` LONGTEXT CHARACTER SET utf8 COLLATE utf8_bin NOT NULL, CHANGE `messageparams` `messageparams` LONGTEXT CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL;

ALTER TABLE `doctrine_tests`.`oc_activity` DROP INDEX `activity_filter_app`, ADD INDEX `activity_filter` (`affecteduser`, `app`, `timestamp`, `type`) USING BTREE;
```


> i dont know, the activity app needs emojis support?

Yes, otherwise if you have emojis in your file names, usernames, calendar events or whatever, it will do :boom:
