### ISSUE TITLE
Shares removed by Nextcloud with no information from Activity App, just Notification

### ISSUE THREAD

**Issue by sunjam** [nextcloud/activity#370]
See [related Notification issue 330](https://github.com/nextcloud/notifications/issues/330)

After upgrading to Nextcloud 16 stable, I see a notification that _Some of your shares were removed_.  However, I'm unable to confirm what was removed via the Activity App or the Notification.  Anytime my shares are removed or changed in this manner, I'd love those specifics to be detailed in my activity log.  Thank you for reading and have a great day.

**Comment by nickvergessen** [comment]
Moved to https://github.com/nextcloud/server/issues/15318
