### ISSUE TITLE
can't load the activity history after the last Maria DB Core Update

### ISSUE THREAD

**Issue by tioannidis** [nextcloud/activity#372]
Activity history are not loaded after OS Updates:

![Activity](https://user-images.githubusercontent.com/1592909/57694775-e8fd0980-764c-11e9-90ae-a8937f96b72e.png)
### Steps to reproduce
1. OS Updates: console-setup console-setup-linux keyboard-configuration mariadb-client-10.1
  mariadb-client-core-10.1 mariadb-common mariadb-server mariadb-server-10.1
  mariadb-server-core-10.1 netplan.io nplan unattended-upgrades

2. Click the activty button 
3. the waiting circle keeps spinning and nothing else appears.
4.in the logs I find after every click on the activity button this error:

> [PHP] Error: TypeError: Argument 1 passed to OCA\Activity\Controller\APIv2::getPreviewPathFromMimeType() must be of the type string, boolean given, called in /var/www/nextcloud/apps/activity/lib/Controller/APIv2.php on line 387 at /var/www/nextcloud/apps/activity/lib/Controller/APIv2.php#407
> 
> GET /nextcloud/ocs/v2.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0
> from 77.7.62.156 by calabama at 2019-05-14T10:50:47+00:00

### Expected behaviour
my activity history

### Actual behaviour

**Operating system**:
Ubuntu 18.04.2 LTS

**Web server:**
Apache2

**Database:**
 mysql  Ver 15.1 Distrib 10.1.38-MariaDB

**PHP version:**
 7.2.17

**Nextcloud version:** (see Nextcloud admin page)
15.0.7.0

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**

  - accessibility: 1.1.0
  - activity: 2.8.2
  - calendar: 1.6.5
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.1
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - news: 13.1.6
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - phonetrack: 0.5.1
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflow_pdf_converter: 1.0.1
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

  "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "zzz"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "overwrite.cli.url": "https:\/\/zzz\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false,
        "loglevel": 2
    }
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
Firefox/66.0","version":"15.0.7.0"
**Operating system:**
Win10
#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

{"reqId":"fV4d4PF33k4WSPPRRQt5","level":3,"time":"2019-05-14T10:57:08+00:00","remoteAddr":"77.7.62.156","user":"**removed**","app":"PHP","method":"GET","url":"/nextcloud/ocs/v2.php/apps/activity/api/v2/activity/by?format=json&previews=true&since=0","message":"TypeError: Argument 1 passed to OCA\\Activity\\Controller\\APIv2::getPreviewPathFromMimeType() must be of the type string, boolean given, called in /var/www/nextcloud/apps/activity/lib/Controller/APIv2.php on line 387 at /var/www/nextcloud/apps/activity/lib/Controller/APIv2.php#407","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0","version":"15.0.7.0","id":"5cda9f046ad04"}

#### Browser log
```
[PHP] Error: TypeError: Argument 1 passed to OCA\Activity\Controller\APIv2::getPreviewPathFromMimeType() must be of the type string, boolean given, called in /var/www/nextcloud/apps/activity/lib/Controller/APIv2.php on line 387 at /var/www/nextcloud/apps/activity/lib/Controller/APIv2.php#407

GET /nextcloud/ocs/v2.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0
from 77.7.62.156 by *removed* at 2019-05-14T10:50:47+00:00
Insert your browser log here, this could for example include:


```

**Comment by nickvergessen** [comment]
Can you modfiy this line:
https://github.com/nextcloud/activity/blob/09446c23ef05204e7372872979f85e29c4f6d9c1/lib/Controller/APIv2.php#L387

to say:
```php
				$preview['source'] = $this->getPreviewPathFromMimeType($fileInfo->getMimetype() ?: 'application/octet-stream');
```

**Comment by tioannidis** [comment]
done, and now it works without errors and no error logs were created.
do you plan to put this change in the next app release?
This nextcloud instance was only a testsystem, I have another productiv machine and I better would wait with the os updates until the next activity release.
Regards,
Theo

**Comment by nickvergessen** [comment]
> do you plan to put this change in the next app release?

yeah sure, but the next release is already in progress so it might be the one afterwards.

**Comment by tioannidis** [comment]
ok, thank you for the quick support.

**Comment by nickvergessen** [comment]
Will be part of 15.0.8 and 16.0.1
