### ISSUE TITLE
File activity not updated reliably when editing with OnlyOffice App

### ISSUE THREAD

**Issue by msumm** [nextcloud/activity#391]
I observe the following problem using Nextcloud 16.0.3 + Activity App 2.9.1 + OnlyOffice App 2.4.0:

Collaborative editing is not reported reliably by the Activity App. Consecutive editing by different users is not tracked by the Activity App, at least not within a certain time interval (several hours). 

**Performed action:**
I consecutively edit a shared docx-file using several user accounts and the OnlyOffice App.
(The file is located on an external WebDAV storage.)

What happens (as long as the Versions App is disabled, see [here](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/118)):
- File is edited
- File editing time is updated
- File is synchronized with external storage & clients
- **The Activity App may or may not track the edits performed by different users. In particular edits made within some hours are not recorded.**

**Expected behaviour:**
Every file edit is recorded within the Activity App, at least if the last editing user changes. Consequently notifications about theses changes are sent to all users having the share.

This problem has already been described in other threads, e. g. [here](https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/57) & [here](https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/27).

Is there any work in progress?

**Comment by nickvergessen** [comment]
This is not a bug in the activity app.
Everytime the file is written to the nextcloud storage an activity is created. So what's missing here is that the OO app does not write the file back to the nextcloud storage.

**Comment by msumm** [comment]
@nickvergessen: I can not confirm your statement that an activity is created **everytime** a file is written to the nextcloud storage.

Though I can not reproduce the case that, when editing a shared docx-file by several users, a change of the last editing user is not listed within the Activity app, the following issue remains:

When editing a shared docx-file several times by the **same user** the last edited time is not shown/updated within the Activity app:

![grafik](https://user-images.githubusercontent.com/53519040/63935029-edfb9280-ca5c-11e9-9dab-59813bb6dc1a.png)

Is this a feature or a bug?
(When multiple edits of the same user are collapsed into a single Activity entry the last edited time should be updated to the last edit?)
Please let me know if I can provide further information regarding this issue.

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/server/pull/17484 should help with that
