### ISSUE TITLE
Activity list in sidebar requires people to click to load more activity

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/activity#398]
Initially only 2 activity items are shown which makes it look very empty, and then you have to click for every ~5 items.

This makes it seem a bit undynamic. Instead we should show as many entries as fit in the height, and lazy load on scroll?

![activity limited](https://user-images.githubusercontent.com/925062/66853370-61ab1d80-ef7f-11e9-96cc-4ceaa8be533c.png)

![activity limited again and guests changes not shown](https://user-images.githubusercontent.com/925062/66853369-61128700-ef7f-11e9-88bd-1ff35433db95.png)

**Comment by nickvergessen** [comment]
There was some problem because the container was not scrollable back then.

Nowadays it's doomed to a potential Vue rewrite when both UIs use the same code

**Comment by joshtrichards** [comment]
This looks done to me.
