### ISSUE TITLE
Time stamp instead of "hours ago" please

### ISSUE THREAD

**Issue by meisterleise** [nextcloud/activity#399]
In the activity timeline I see things like "1 hour ago", "10 hours ago" and so on. So I'm calculating all the day. What time was it 7 hours ago?
In the android app I have absolute time stamps. I'd find that much better!

Please think about it. 
Thank you very much for this plugin!

**Comment by nickvergessen** [comment]
Totally agree... @jancborchardt

**Comment by jancborchardt** [comment]
The thinking behind it is that when you see "1 hour ago" it’s much easier to know it was recent than when you see "11:56". Also the timestamp shows on hover, but yes that might not be discoverable.

So I have no strong opinion in this case, @nickvergessen feel free to change it to absolute timestamps.

**Comment by meisterleise** [comment]
Wow, I never noticed that there is a hover! :D Very nice!
Okay, I'd still prefer a time stamp, but since I've a hover now, I could live with that.

**Comment by DarkknightAK** [comment]
closed or open?

**Comment by meisterleise** [comment]
I would say closed.
