### ISSUE TITLE
Wrong activity "owner" when more than one person edits an office document online

### ISSUE THREAD

**Issue by oparoz** [nextcloud/activity#40]
### Steps to reproduce
1. Ask someone to open a document using Collabora Office
1. Open the same document using Collabora Office
1. Take editing control
1. Make modifications

### Expected behaviour

I should be shown as the author in the activity stream

### Actual behaviour

The other person is shown as the author

### Server configuration
**Operating system**: LR Hardened Linux Primo 3+

**Nextcloud version:** 10

**Where did you install Nextcloud from:** tarball

**Comment by nickvergessen** [comment]
With 10 or master?

**Comment by oparoz** [comment]
With 10

**Comment by nickvergessen** [comment]
This works "normal" for text files, I reproduced with with an odt using the "richtdocuments" app. So it seem that this app is doing changes only for the first user that ever opened the file, until all users close the editor again.

Please report this to the app author of the other app. They seem to use a wrong user when editing the files. Nothing the activity app can take care of.

**Comment by oparoz** [comment]
Thanks for looking into this :)
