### ISSUE TITLE
Does calendar events mandatory?

### ISSUE THREAD

**Issue by Irillit** [nextcloud/activity#401]
No matter what applications you enable, you'll have these entries:
![image](https://user-images.githubusercontent.com/26794757/67680997-80f17400-f99d-11e9-9711-2b36f8c1b2e3.png)

1) Am I right that these activities are connected to Calendar app? 
2) Is it ok to remove them when calendar was disabled?

**Comment by nickvergessen** [comment]
Those are always there as the backend for calendars is always enabled and can be interactes with any clients also when the calendar app is not there

**Comment by Irillit** [comment]
1) Does it mean even if you disabled calendar, it might notify you?
2) Can we change calendar throgh any app?

**Comment by nickvergessen** [comment]
> Can we change calendar throgh any app?

We provide a CalDAV Backend. It's widely spread technology. You can create events in thunderbird, android and ios default calendars, and many more.

> Does it mean even if you disabled calendar, it might notify you?

yes. If you want to get rid of it, you can remove the following lines from `/apps/dav/appinfo/info.xml`:
https://github.com/nextcloud/server/blob/04ef434af079e22ef27a874975970fde4ae93961/apps/dav/appinfo/info.xml#L60-L77

But:
1. You have to do that after every nextcloud update
2. You will receive a warning that the file is modified

**Comment by Irillit** [comment]
Thank you!
