### ISSUE TITLE
Exception when opening file anonymously

### ISSUE THREAD

**Issue by rasos** [nextcloud/activity#410]
### Steps to reproduce
1. Open shared folder anonymously
2. Open PDF

### Expected behaviour
PDF opens in browser

### Actual behaviour
500 error

Log: `An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'`

The PDF opens in logged in mode normally.

When de-activating the Activity App, the file opens normally also anonymously.

### Server configuration

**Operating system**:

Ubuntu 18.04

**Web server:**

Apache

**Database:**

mySQL

**PHP version:**

7.2.24

**Nextcloud version:** (see Nextcloud admin page)

16.0.6

**Where did you install Nextcloud from:**

several upgrades since owncloud 8

LDAP auth

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"XeDPoQxjkaI7ku0XZ4WqhwAAAB4","level":3,"time":"2019-11-29T07:58:26+00:00","remoteAddr":"194.208.212.51","user":"--","app":"index","method":"GET","url":"/nextcloud/index.php/s/ZGa2A3oZsSKzHFy/download?path=%2F&files=A%20framework%20business%20models.pdf","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files_sharing\", \"public_shared_file_downloaded\", \"[\\\"\\\\\\/O\\\\\\/O Guideline | Entrepreneurship\\\\\\/A framework business models.pdf\\\"]\", \"\", \"[]\", \"\\/O\\/O Guideline | Entrepreneurship\\/A framework business models.pdf\", \"\", \"\", \"m@abc.org\", 1575014306, 30, \"public_links\", \"files\", 4060581]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'public_links' for column 'type' at row 1","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":184,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files_sharing\", \"public_shared_file_downloaded\", \"[\\\"\\\\\\/O\\\\\\/ Guideline | Entrepreneurship\\\\\\/A framework business models.pdf\\\"]\", \"\", \"[]\", \"\\/O\\/Guideline | Entrepreneurship\\/A framework business models_.pdf\", \"\", \"\", \"m@abc.com\", 1575014306, 30, \"public_links\", \"files\", 4060581]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'public_links' for column 'type' at row 1",{"errorInfo":["HY000",1366,"Incorrect integer value: 'public_links' for column 'type' at row 1"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":158,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["HY000",1366,"Incorrect integer value: 'public_links' for column 'type' at row 1"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files_sharing\", \"public_shared_file_downloaded\", \"[\\\"\\\\\\/project1\\\\\\/projectguide | E2R\\\\\\/A framework business models.pdf\\\"]\", \"\", \"[]\", \"\\/ABC\\/ABCG | E234\\/A framework business models_final.pdf\"
(truncated due to more privacy relevant data, repeating above errors)
}
```

**Comment by nickvergessen** [comment]
The error says your database table `oc_activity` has a column `type` which is an integer. But actually we create it as string.

Can you run the following query and show the result?
```sql
DESCRIBE `oc_activity`;
```

**Comment by rasos** [comment]
| Field | Type | Null | Key | Default | Extra |  
| -- | -- | -- | -- | -- | -- | --
| activity_id | bigint(20) | NO | PRI | NULL | auto_increment
| timestamp | int(11) | NO |   | 0 |  
| priority | int(11) | NO |   | 0 |  
| type | int(11) | NO |   | 0 |  
| user | varchar(255) | NO |   | NULL |  
| affecteduser | varchar(255) | NO |   | NULL |  
| app | varchar(255) | NO |   | NULL |  
| subject | varchar(255) | NO |   | NULL |  
| subjectparams | varchar(255) | NO |   | NULL |  
| message | varchar(255) | YES |   | NULL |  
| messageparams | varchar(255) | YES |   | NULL |  
| file | varchar(255) | YES |   | NULL |  
| link | varchar(255) | YES |   | NULL |  
| object_type | varchar(255) | YES | MUL | NULL |  
| object_id | bigint(20) | NO |   | 0 |

**Comment by nickvergessen** [comment]
| Field         | Type          | Null | Key | Default | Extra          |
|---------------|---------------|------|-----|---------|----------------|
| activity_id   | bigint(20)    | NO   | PRI | NULL    | auto_increment |
| timestamp     | int(11)       | NO   |     | 0       |                |
| priority      | int(11)       | NO   |     | 0       |                |
| type          | varchar(255)  | YES  |     | NULL    |                |
| user          | varchar(64)   | YES  |     | NULL    |                |
| affecteduser  | varchar(64)   | NO   | MUL | NULL    |                |
| app           | varchar(32)   | NO   |     | NULL    |                |
| subject       | varchar(255)  | NO   |     | NULL    |                |
| subjectparams | longtext      | NO   |     | NULL    |                |
| message       | varchar(255)  | YES  |     | NULL    |                |
| messageparams | longtext      | YES  |     | NULL    |                |
| file          | varchar(4000) | YES  |     | NULL    |                |
| link          | varchar(4000) | YES  |     | NULL    |                |
| object_type   | varchar(255)  | YES  | MUL | NULL    |                |
| object_id     | bigint(20)    | NO   |     | 0       |                |

Seems like your table is heavily corrupted. It should look like above.
Maybe you can manually fix this?

**Comment by rasos** [comment]
Table fixed manually and now `Activity` works as expected. Also `Deck` now accepts notes. Must have an issue with an update script some time ago. Thanks for the hint.
