### ISSUE TITLE
activity layout update

### ISSUE THREAD

**Issue by DarkknightAK** [nextcloud/activity#416]
The activity view is now very text based which save space when you have more activities with the same activity and user, but you have any filter feature. In addition the activity layout is complete different to any other layout so it don't use layouts that are already available and more flexible.

I recommend to have something that is more like settings -> logging or the generic file view.

![Logging](https://user-images.githubusercontent.com/8517736/71959659-86680780-31f3-11ea-90db-86afa32ff6f3.png)

anyway it would be nice to have an filter item like it is available in logging so you can filter after activities from Lavel, User, File type, Folder (show only folders with name Report or show only activities from selected subfolder, activities between time, ...)

![layout](https://user-images.githubusercontent.com/8517736/71959953-2d4ca380-31f4-11ea-9ae6-02d03f61b8f1.png)

**Comment by DarkknightAK** [comment]
have something like an table layout (.csv) give you the option to postprocess the activity stream.

csv is requested by #82

**Comment by nickvergessen** [comment]
This is not what we are aiming for with the activity app.
You can achieve this better with the admin_audit app.
