### ISSUE TITLE
How to force sending of activity mail via command line

### ISSUE THREAD

**Issue by CombeeMike** [nextcloud/activity#427]
This is no feature request but a question so I'm not filling in the "form":

* Is it possible to force sending of the activity mail manually via the command line (e.g. some `occ:...` command)?
* Also is it possible to do this without "resetting" the current state to allow sending of the mail with the same content multiple times?

Use case: I'm about to implement some “custom adjustments” to the mail content and would really appreciate if I could test those changes right away instead of having to wait for the next cron job.

Same question was already asked in the [help forum](https://help.nextcloud.com/t/force-activity-mail/14494) some time ago but I thought it might have better chance of being answered here ;)

**Comment by nickvergessen** [comment]
There is an occ command: https://www.schilljs.com/2017/05/09/better-scheduling-of-activity-emails.html

> Also is it possible to do this without "resetting" the current state to allow sending of the mail with the same content multiple times?

No

**Comment by CombeeMike** [comment]
Ok, thanks for the info! Could you point me in the direction where the "queue reset" is happening inside the code? This way I could comment the relevant code out during debugging...

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/activity/blob/master/lib/MailQueueHandler.php#L485

Just to make this clear. If you modify the existing email template, you might run into issues on any update in the future. Instead you should follow this: https://portal.nextcloud.com/article/customized-email-templates-29.html

**Comment by CombeeMike** [comment]
Perfect, thank you for the info!

I'm not adjusting the template but am removing items I'm not interested in which is most probably not possible with templating...

See [my comment](https://github.com/nextcloud/activity/issues/135#issuecomment-578474837) in #135.

Also I'm fully aware of the fact that my changes in the code are lost or can cause troubles on updates. Thanks for the heads up!
