### ISSUE TITLE
notice of file downloads via IP capture and email to admin

### ISSUE THREAD

**Issue by enoch85** [nextcloud/activity#434]
*Copied from https://github.com/owncloud/activity/issues/350*

Hi - not sure where to put this suggestion for improving the Activity app but for me the most important activity that i'd want to track is not currently available with this app and that is an alert of when files are downloaded from shares ... ideally as admin i would love to get email (or peruse a log file) with the IP address along with date-time stamp of which files are being downloaded ... this would help in the event a file was being overly shared - meaning if i had private link that i sent to one person and then saw ten download notices from ten different IP addresses for that share, i would be alerted to the fact that the share link got out into the wild and therefore shut it down to block further shares ... perhaps this IP tracking downloads feature / functionality belongs in its own app / plugin ..??.. suffice it to say, i would love to know when and from where files are being accessed ... the activity within ownCloud of new users created, shares created, etc is not nearly as important IMHO as knowing activity like how often files are being downloaded / accessed and from what IPs ...

**Comment by ccsric** [comment]
Hi, great idea.

**Comment by szaimen** [comment]
It was decided to not implement this feature because of dsgvo reasons. You can though use this app if you need this feature badly: https://apps.nextcloud.com/apps/files_trackdownloads
