### ISSUE TITLE
app never finishes loading the activities tab

### ISSUE THREAD

**Issue by mightyBroccoli** [nextcloud/activity#440]
[no app in context] Error: Exception: substr() expects parameter 3 to be int, bool given at <<closure>>

0. /var/www/example.de/cloud.example.de/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Activity\Controller\APIv2 {}, "getFilter")
1. /var/www/example.de/cloud.example.de/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("APIv2Controller", "getFilter", OC\AppFramework\ ... {}, {filter: "all",_ ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({filter: "all",_ ... "})
3. /var/www/example.de/cloud.example.de/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {filter: "all",_ ... "})
4. /var/www/example.de/cloud.example.de/ocs/v1.php line 82
   OC\Route\Router->match("/ocsapp/apps/ac ... l")
5. /var/www/example.de/cloud.example.de/ocs/v2.php line 24
   require_once("/var/www/magicb ... p")

GET /ocs/v2.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0
from 2.205.105.21 by nico at 2020-03-19T22:42:15+01:00

**Comment by nickvergessen** [comment]
do you have custom mimetypes in place or are you using an old veresion of the mindmap app?

**Comment by mightyBroccoli** [comment]
No I do not have custom mime types.
I am running mindmap version 0.0.20. But indeed after disabeling the mindmap app the activities app is usable again.

**Comment by nickvergessen** [comment]
aparently this was fixed in 0.0.18:

https://github.com/ACTom/files_mindmap/issues/84
