### ISSUE TITLE
Click on meeting name opens the meeting in the calendar

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/activity#444]
It would be nice, If a click on meeting name opens the meeting in the calendar (link it does when I click on a file name)

### Actual behaviour
Nothing happens

![grafik](https://user-images.githubusercontent.com/24530680/77749597-93420d80-7022-11ea-8def-67b86a093a52.png)

**Comment by nickvergessen** [comment]
Work in progress: https://github.com/nextcloud/activity/pull/420

**Comment by pierreozoux** [comment]
The PR was merged, and I can see the functionnality. Closing.
