### ISSUE TITLE
[Feature Request] Show activity of all users in group folders

### ISSUE THREAD

**Issue by nooblag** [nextcloud/activity#479]
Requesting the ability for all activity occurring in group folders (additions, modifications, deletions) to appear in Activity tab.

**Comment by fschrempf** [comment]
Also see https://github.com/nextcloud/groupfolders/issues/1018

**Comment by fschrempf** [comment]
Create, modify and delete already works for groupfolders. With #693 move and rename should also be covered. Let's track missing groupfolder activities like sharing in nextcloud/groupfolders#1018.
