### ISSUE TITLE
Activity/more link escaping

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/activity#5]
I noticed that there seems to be an escaping issue in the activity log, see screenshot.

![escaping](https://cloud.githubusercontent.com/assets/6607975/16889268/061daf42-4a9a-11e6-8a7e-2cd0c02dacf1.png)

### Steps to reproduce
1. New account with hostiso.com

### Expected behaviour
Proper variable escaping

### Actual behaviour
Resulting HTML shows:

`<strong data-original-title="Photos/San Francisco.jpg, Photos, <a class=" class="has-tooltip" title="" filename="" has-tooltip"="" href="http://nc.hostiso.cloud/index.php/apps/files/?dir=/">">4 more</strong>`

Copy of https://github.com/nextcloud/server/issues/420

**Comment by MorrisJobke** [comment]
cc @rendezvousIY

**Comment by nickvergessen** [comment]
@rendezvousIY can you use your browser tools and inspect the server response of the activity API call, I fail to find an easy way to reproduce this.
