### ISSUE TITLE
No calendar activity logged since upgrade to NC20 beta/RC

### ISSUE THREAD

**Issue by kchan101** [nextcloud/activity#501]
### Steps to reproduce
1. Create or modify calendar entry
2. Check Activity tab

### Expected behaviour
Expect to see calendar activity entries

### Actual behaviour
No calendar activity recorded

**Comment by kaleb** [comment]
I freshly installed NC20 and do not see the activity app available to install from the store.

**Comment by joshtrichards** [comment]
Definitely not the case today. Closing.
