### ISSUE TITLE
User ID and reverse proxy IP shown in the Activity

### ISSUE THREAD

**Issue by mikoladz** [nextcloud/activity#502]
### Steps to reproduce
1. Login to NC with LDAP user account.
2. Share any file with any other NC user.
3. Once the other user downloads the file check the activity for it.

### Expected behaviour
I would like to see real user name who downloaded the file. I would also like to see the real client IP, or at least not see the reverse proxy IP. 

### Actual behaviour
In the activity for the file I see LDAP user ID and reverse proxy IP, eg.:
"Shared file example.txt was downloaded by 9(
91234qwer-56ty-98as-8520-147852yuio12 (IP: 192.168.1.212) via the browser"
"91234qwer-56ty-98as-8520-147852yuio12" is the user ID in LDAP, and the IP belongs to the reverse proxy in front of NC.

### Server configuration

**Operating system**:
Debian GNU Linux
**Web server:**
Apache 2.4.38
**Database:**
MariaDB 10.1.44
**PHP version:**
PHP 7.3
**Nextcloud version:** (see Nextcloud admin page)
19.0.3
**Where did you install Nextcloud from:**
Official package from nextcloud.com
**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
  - accessibility: 1.5.0
  - activity: 2.12.0
  - apporder: 0.11.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.0
  - contactsinteraction: 1.0.0
  - cospend: 1.0.5
  - dav: 1.15.0
  - documentserver_community: 0.1.7
  - event_update_notification: 1.0.2
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_retention: 1.8.2
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trackdownloads: 1.8.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - gpxpod: 4.2.2
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - metadata: 0.12.0
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - ocsms: 2.1.8
  - onlyoffice: 6.0.0
  - password_policy: 1.9.1
  - phonetrack: 0.6.4
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - socialsharing_email: 2.1.0
  - spreed: 9.0.4
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.3
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.9.0
  - user_ldap: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.2.114",
            "REMOVED",
            "*.REMOVED"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/REMOVED\/",
        "dbtype": "mysql",
        "version": "19.0.3.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "htaccess.RewriteBase": "\/",
        "overwriteprotocol": "https",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "stable",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "lost_password_link": "https:\/\/REMOVED",
        "remember_login_cookie_lifetime": 604800,
        "session_lifetime": 28800,
        "session_keepalive": true,
        "trashbin_retention_obligation": "auto, 30",
        "simpleSignUpLink.shown": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    }
}

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP (FreeIPA)
### Client configuration
**Browser:**
Firefox 68
**Operating system:**
Debian GNU Linux
#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
Below is an excerpt from the log from the time the shared files were downloaded:

{"reqId":"UkNnxY0w9NciaVvZwHFi","level":0,"time":"2020-10-01T08:39:00+00:00","remoteAddr":"1.2.3.4","user":"--","app":"user_ldap","method":"POST","url":"/login","message":"No DN found for USER on LDAP_SERVER","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"XUkIONQsWueuneh3jysI","level":0,"time":"2020-10-01T08:39:02+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"XUkIONQsWueuneh3jysI","level":0,"time":"2020-10-01T08:39:02+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"XUkIONQsWueuneh3jysI","level":0,"time":"2020-10-01T08:39:02+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"XUkIONQsWueuneh3jysI","level":0,"time":"2020-10-01T08:39:02+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"XUkIONQsWueuneh3jysI","level":0,"time":"2020-10-01T08:39:02+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"XUkIONQsWueuneh3jysI","level":0,"time":"2020-10-01T08:39:02+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"XUkIONQsWueuneh3jysI","level":0,"time":"2020-10-01T08:39:02+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"jGmyoAAjAMhsBt6oulTH","level":0,"time":"2020-10-01T08:39:17+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=28942&c=58148cf7753b81f23d400d6a28084424&x=250&y=250&forceIcon=0","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"zjpZGNN3UJLaSauggDEb","level":0,"time":"2020-10-01T08:39:17+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=34512&c=424f62a5d763fcf68a5df7cb29f21c5b&x=250&y=250&forceIcon=0","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"XgJ2e4QBLgKIIuV4J9ye","level":0,"time":"2020-10-01T08:39:17+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=34468&c=e54fb8a73294965504459a41ad251a08&x=250&y=250&forceIcon=0","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"8zOjepvJICyigeMDX4Yo","level":0,"time":"2020-10-01T08:39:17+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1591&c=a96fe8f67aa6e5d45ca6fea0d1966cc2&x=250&y=250&forceIcon=0","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"5ZY6m5H8pMxqrnogpW15","level":0,"time":"2020-10-01T08:39:17+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1912&x=32&y=32","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"5ZY6m5H8pMxqrnogpW15","level":0,"time":"2020-10-01T08:39:17+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1912&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"5ZY6m5H8pMxqrnogpW15","level":0,"time":"2020-10-01T08:39:17+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1912&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::preCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"wdGmL2L8ntfH6SJMYl9c","level":0,"time":"2020-10-01T08:39:17+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=774&c=578bc50935ae5655296d577cfaa51a0e&x=250&y=250&forceIcon=0","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"5ZY6m5H8pMxqrnogpW15","level":0,"time":"2020-10-01T08:39:17+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1912&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"5ZY6m5H8pMxqrnogpW15","level":0,"time":"2020-10-01T08:39:17+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1912&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::postCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"bn6ARr1kn1K2p7zBJxwE","level":0,"time":"2020-10-01T08:39:18+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=775&c=d42ce6675ae8cf67676aa06884a8003a&x=250&y=250&forceIcon=0","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"uixnNDtgxqHfS9awxoxh","level":0,"time":"2020-10-01T08:39:18+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=50515&x=32&y=32","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"OFaKBa1bhGztdWTTBATX","level":0,"time":"2020-10-01T08:39:18+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1908&x=32&y=32","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"5ZY6m5H8pMxqrnogpW15","level":0,"time":"2020-10-01T08:39:18+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1912&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"5ZY6m5H8pMxqrnogpW15","level":0,"time":"2020-10-01T08:39:18+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1912&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::preCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"5ZY6m5H8pMxqrnogpW15","level":0,"time":"2020-10-01T08:39:18+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1912&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"5ZY6m5H8pMxqrnogpW15","level":0,"time":"2020-10-01T08:39:18+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1912&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::postCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"OFaKBa1bhGztdWTTBATX","level":0,"time":"2020-10-01T08:39:19+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1908&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"OFaKBa1bhGztdWTTBATX","level":0,"time":"2020-10-01T08:39:19+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1908&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::preCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"gJCVSasZsZxiwieDUKeK","level":0,"time":"2020-10-01T08:39:19+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=31542&c=cfb0e9cf58b2f056af97ab59539d9ac0&x=250&y=250&forceIcon=0","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"OFaKBa1bhGztdWTTBATX","level":0,"time":"2020-10-01T08:39:19+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1908&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"OFaKBa1bhGztdWTTBATX","level":0,"time":"2020-10-01T08:39:19+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1908&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::postCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"9cFStwjtA3sMVmxu8oco","level":0,"time":"2020-10-01T08:39:22+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=35044&c=f87db435e0f5edbb3d95b5096495f8ba&x=250&y=250&forceIcon=0","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"OFaKBa1bhGztdWTTBATX","level":0,"time":"2020-10-01T08:39:23+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1908&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"OFaKBa1bhGztdWTTBATX","level":0,"time":"2020-10-01T08:39:23+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1908&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::preCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"OFaKBa1bhGztdWTTBATX","level":0,"time":"2020-10-01T08:39:24+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1908&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"OFaKBa1bhGztdWTTBATX","level":0,"time":"2020-10-01T08:39:24+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1908&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::postCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"5ZY6m5H8pMxqrnogpW15","level":0,"time":"2020-10-01T08:39:24+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1912&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"5ZY6m5H8pMxqrnogpW15","level":0,"time":"2020-10-01T08:39:24+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1912&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::preCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"5ZY6m5H8pMxqrnogpW15","level":0,"time":"2020-10-01T08:39:24+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1912&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"5ZY6m5H8pMxqrnogpW15","level":0,"time":"2020-10-01T08:39:24+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1912&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::postCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"OFaKBa1bhGztdWTTBATX","level":0,"time":"2020-10-01T08:39:24+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1908&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"OFaKBa1bhGztdWTTBATX","level":0,"time":"2020-10-01T08:39:24+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1908&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::preCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"OFaKBa1bhGztdWTTBATX","level":0,"time":"2020-10-01T08:39:24+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1908&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
{"reqId":"OFaKBa1bhGztdWTTBATX","level":0,"time":"2020-10-01T08:39:24+00:00","remoteAddr":"1.2.3.4","user":"91234qwer-56ty-98as-8520-147852yuio12","app":"no app in context","method":"GET","url":"/core/preview?fileId=1908&x=32&y=32","message":"Deprecated event type for \\OCP\\Files::postCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by plaing1** [comment]
Same here, reverse proxy IP is shown under activity instead of client IP.

Setting 'trusted_proxies' and 'forwarded_for_headers' doesn't help.

Nextcloud: 19.0.6.2
Server: Ubuntu 20.04.1 LTS

**Comment by szaimen** [comment]
this is happen due to.
https://apps.nextcloud.com/apps/files_trackdownloads
Feel free to report it there.
