### ISSUE TITLE
amq_subjectparams has a different size than subjectparams

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/activity#503]
The subjectparams table of oc_activity_mq has a size limit of 4000 characters while the subjectparams of oc_activity are a longtext column. 

@nickvergessen Is there any reasoning behind that? Wouldn't it make sense to have a longtext for the mq table as well, since otherwise activity entries might not be added to the mq table if the subject params json exceeds 4000 chars.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/activity/blob/347991a049c2a39d64b7c5a2aa0373cfd014f9e2/lib/Migration/Version2006Date20170808154933.php#L81-L83

It's text saves up to 65k chars. If you have a 4k char you had the app disabled when updating from I think oc 8 to 8.1
We could add a migration to try the conversation again, but it's not happening anymore, so it's plain for people migrating very old instances.

**Comment by nickvergessen** [comment]
Oh wait, `amq_subjectparams` is ...

well yeah no reason for that... needs fixing asap.
