### ISSUE TITLE
"You attended a call with ..." as notification

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/activity#521]
Should this be a server notification? Currently it is:
![grafik](https://user-images.githubusercontent.com/24530680/97264759-d321db00-1825-11eb-98f2-4c31f1087624.png)

**Comment by joshtrichards** [comment]
This was possible when push notifications were on w/ Talk. 

https://github.com/nextcloud/spreed/issues/6302#issuecomment-930971389

No longer possible:

nextcloud/spreed#6303
