### ISSUE TITLE
Activities visible but no email nor push notification at all (NC 20.0.1 Docker)

### ISSUE THREAD

**Issue by cho0p** [nextcloud/activity#526]
### Steps to reproduce
1. Configure Activity App
2. Add/remove/edit etc. any file
3. Activity visible in web frontend (.../apps/activity/) but no Email or push notification visible

### Expected behaviour
An Email should be send out as well as a push notification should be visible

### Actual behaviour
The activity is visible in the app / web frontend but no Email nor push notification comes through

### Server configuration

**Operating system**: Linux 4.19.0-12-amd64 x86_64 (host)

**Web server:**

**Database:** MariaDB mysql

**PHP version:** 7.4.12

**Nextcloud version:** 20.0.1 Docker

**Where did you install Nextcloud from:** https://github.com/nextcloud/docker

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

No errors have been found.

Cron is properly configured as mentioned in the docs. Email is also working - I can generate and receive the Nextcloud test email. 

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.2
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - joplin: 0.0.25
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.X.X:XXXX",
            "xxx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.1.1",
        "overwrite.cli.url": "http:\/\/192.168.X.XX:XXXX",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "Benutzer",
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "app_install_overwrite": [
            "joplin"
        ],
        "loglevel": 1,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable"
    }

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

Firefox 82.0.2 64 Bit

**Operating system:**

Windows 10

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"LFU0ZnMj3DtpfBCAs6q6","level":1,"time":"2020-11-09T16:48:00+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav/","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.1","version":"20.0.1.1"}
{"reqId":"kfLXdjrKCP3G9t5SJmnk","level":1,"time":"2020-11-09T16:48:00+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav/","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.1","version":"20.0.1.1"}
{"reqId":"jP1BVzPNVZ4mTjf8LmzR","level":1,"time":"2020-11-09T17:03:11+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav/","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.1","version":"20.0.1.1"}
{"reqId":"64aAvPZ2KWAJJfYBrTfv","level":1,"time":"2020-11-09T17:03:11+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav/","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.1","version":"20.0.1.1"}
{"reqId":"sEhmim55Y2YYMOhKszPd","level":1,"time":"2020-11-09T17:18:53+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav/","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.1","version":"20.0.1.1"}
{"reqId":"dueYTQPeGPvA8xPCCEcx","level":1,"time":"2020-11-09T17:18:53+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav/","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.1","version":"20.0.1.1"}
{"reqId":"zdyH3K5o8DWtAPWol2Kf","level":1,"time":"2020-11-09T17:35:34+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav/","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.1","version":"20.0.1.1"}
{"reqId":"joHwpoiEj4Fe3eyDaJ9T","level":1,"time":"2020-11-09T17:43:42+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1"}
{"reqId":"wS5DZFPLrVRpFO5eI2tz","level":1,"time":"2020-11-09T17:43:43+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Deprecated event type for OCP\\IDBConnection::CHECK_MISSING_INDEXES: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1"}
{"reqId":"wS5DZFPLrVRpFO5eI2tz","level":1,"time":"2020-11-09T17:43:43+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Deprecated event type for OCP\\IDBConnection::CHECK_MISSING_INDEXES: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1"}
{"reqId":"wS5DZFPLrVRpFO5eI2tz","level":1,"time":"2020-11-09T17:43:43+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Deprecated event type for OCP\\IDBConnection::CHECK_MISSING_COLUMNS: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1"}
{"reqId":"wS5DZFPLrVRpFO5eI2tz","level":1,"time":"2020-11-09T17:43:43+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Deprecated event type for OCP\\IDBConnection::CHECK_MISSING_COLUMNS: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1"}
{"reqId":"bxiwcm7YJjqOjTiglWgr","level":1,"time":"2020-11-09T17:49:35+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1"}
{"reqId":"U8YAuRP9GUgLC3l1HdUE","level":1,"time":"2020-11-09T17:49:37+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Deprecated event type for OCP\\IDBConnection::CHECK_MISSING_INDEXES: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1"}
{"reqId":"U8YAuRP9GUgLC3l1HdUE","level":1,"time":"2020-11-09T17:49:37+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Deprecated event type for OCP\\IDBConnection::CHECK_MISSING_INDEXES: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1"}
{"reqId":"U8YAuRP9GUgLC3l1HdUE","level":1,"time":"2020-11-09T17:49:37+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Deprecated event type for OCP\\IDBConnection::CHECK_MISSING_COLUMNS: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1"}
{"reqId":"U8YAuRP9GUgLC3l1HdUE","level":1,"time":"2020-11-09T17:49:37+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"GET","url":"/settings/ajax/checksetup","message":"Deprecated event type for OCP\\IDBConnection::CHECK_MISSING_COLUMNS: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1"}
{"reqId":"bR4MearKN0s14nKmamtq","level":1,"time":"2020-11-09T17:51:06+00:00","remoteAddr":"89.56.137.36","user":"username","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav/","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.1","version":"20.0.1.1"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

![activity_cron](https://user-images.githubusercontent.com/42189739/98578577-d30dea80-22bd-11eb-90e9-5a2a95f278a6.JPG)
![activity](https://user-images.githubusercontent.com/42189739/98578579-d3a68100-22bd-11eb-9a8e-7ba5b7612ad5.JPG)
![activity_conf](https://user-images.githubusercontent.com/42189739/98578580-d3a68100-22bd-11eb-9e6c-9ea245c5e1fe.JPG)

**Comment by GloomPanther** [comment]
Same problems without Docker, only a clean Debian installation with Apache2

**Comment by cho0p** [comment]
I am also still facing those issues without any solution yet.

**Comment by tbart** [comment]
I have the same issue, although on 19.x.

We can possibly try to narrow down the issue a little.

I *do* get notifications if I call
`sudo -u ${nextcloud-user} php ${wwwroot}/occ activity:send-mails`

so it seems the activity app's job does not register correctly for being picked up in the cron run.
Can someone verify if this is the case for 20.x as well?

**Comment by top-logic** [comment]
Same problem on NC21.

**Comment by tobyps** [comment]
> 
> 
> Same problem on NC21 with favorite activities.
> Also occ activity:send-mails not sending an email or ringing the notify bell.
> Other info mails like "some one shared a file to you" are no problem.

Same here, the activities are logged and displayed in the activity app but no Mails or Push Notification.
And no Errors in the Nextcloudlog.

**Comment by flaviovs** [comment]
If it helps, here's the result of tests made on a fresh Debian (non-docker) install:

:black_square_button:  *A file or folder has been changed*
:ballot_box_with_check: *A file has been added to or removed from your favorites*

- cron.php - no emails
- occ activity:send-mails - no emails

:ballot_box_with_check:  *A file or folder has been changed*
:ballot_box_with_check: *A file has been added to or removed from your favorites*
 
- cron.php - no emails
- occ activity:send-mails - email sent :tada: 

Tested with "Send email notifications" set to "as soon as possible" and "Hourly" -- same result for both.

So I'd say there are two issues here:

1. "A file has been added to or removed from your favorites" only works if "A file or folder has been changed" is checked (which is far from ideal, BTW)
2. cron.php alone is not enough for email notifications to be actually sent out

**Comment by seantunley** [comment]
Same issue on NextCloud21 with favorite activities.

Other info mails like "some one shared a file to you" are no problem.

It is not ideal to have the change email notification on for a large organization with tons of files

**Comment by nik0chan** [comment]
Same issue here,

Operating system: CentOS Linux release 8.2.2004 (Core)

Web server:
nginx/1.14.1

Server version: Apache/2.4.37 (centos)
Server built: Sep 15 2020 15:41:16

Database: MariaDB Ver 15.1 Distrib 10.3.17-MariaDB, for Linux (x86_64) using readline 5.1

PHP version: 7.4.13

Nextcloud version: 20.0.11 no Docker

sudo -u nginx php -f /var/www/nextcloud/occ app:list
Enabled:

    accessibility: 1.6.0
    activity: 2.13.4
    admin_audit: 1.10.0
    apporder: 0.13.0
    bruteforcesettings: 2.2.0
    calendar: 2.3.3
    circles: 0.20.11
    cloud_federation_api: 1.3.0
    comments: 1.10.0
    contactsinteraction: 1.1.0
    customproperties: 2.0.4
    dav: 1.16.2
    deck: 1.2.8
    event_update_notification: 1.3.0
    external: 3.7.3
    extract: 1.3.2
    federatedfilesharing: 1.10.2
    federation: 1.10.1
    files: 1.15.0
    files_accesscontrol: 1.10.2
    files_antivirus: 3.2.1
    files_automatedtagging: 1.10.1
    files_downloadactivity: 1.9.0
    files_external: 1.11.1
    files_markdown: 2.3.4
    files_pdfviewer: 2.0.1
    files_rightclick: 0.17.0
    files_sharing: 1.12.2
    files_trackdownloads: 1.9.0
    files_trashbin: 1.10.1
    files_versions: 1.13.0
    files_videoplayer: 1.9.0
    firstrunwizard: 2.9.0
    forms: 2.3.0
    geoblocker: 0.5.1
    group_everyone: 0.1.8
    guests: 1.6.3
    impersonate: 1.7.0
    ldap_contacts_backend: 1.0.1
    logreader: 2.5.0
    lookup_server_connector: 1.8.0
    metadata: 0.14.0
    nextcloud_announcements: 1.9.0
    notes: 4.1.1
    notifications: 2.8.0
    oauth2: 1.8.0
    onlyoffice: 7.1.2
    password_policy: 1.10.1
    privacy: 1.4.0
    provisioning_api: 1.10.0
    qownnotesapi: 21.7.0
    quickaccesssorting: 1.1.2
    ransomware_protection: 1.11.0
    serverinfo: 1.10.0
    settings: 1.2.0
    sharebymail: 1.10.0
    side_menu: 1.27.2
    support: 1.3.0
    survey_client: 1.8.0
    suspicious_login: 3.2.1
    systemtags: 1.10.0
    tasks: 0.14.2
    text: 3.1.0
    theming: 1.11.0
    twofactor_backupcodes: 1.9.0
    updatenotification: 1.10.0
    user_ldap: 1.10.2
    user_saml: 3.3.5
    user_status: 1.0.1
    user_usage_report: 1.4.2
    viewer: 1.4.0
    workflowengine: 2.2.0
    Disabled:
    dashboard
    encryption
    photos
    recommendations
    weather_status

MTA agent: postfix-3.5.8-1.el8

**Comment by szaimen** [comment]
Will be resolved with https://github.com/nextcloud/server/pull/28853
