### ISSUE TITLE
more info about downloads of public links

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/activity#529]
I'd like to know what link exactly was downloaded (if a file has multiple share links you can identify them by name - as we can now name links).

Second, it'd be nice to know where it was downloaded from - either as IP address, or even use a geo lookup for a bit more info.

**Comment by gitHost7** [comment]
+1 from me - also would like to see the name of the link in the activity

**Comment by szaimen** [comment]
It was decided to not implement this feature because of dsgvo reasons. You can though use this app if you need this feature badly: https://apps.nextcloud.com/apps/files_trackdownloads

**Comment by squintarelli** [comment]
It seems strange to me.
it looks like being over-adherence to the regulation
there are a number of use cases that require exactly this type of tracking, and many EU platforms providing it.
(sales, marketing, finance...)

**Comment by nickvergessen** [comment]
> it looks like being over-adherence to the regulation
there are a number of use cases that require exactly this type of tracking, and many EU platforms providing it.
(sales, marketing, finance...)

For those regulations there is the `admin_audit` app which stores this information in a much faster and machine readable way:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#admin-audit-log

**Comment by squintarelli** [comment]
Thank you for the link
Besides sales/mktg, there are a number of regulated activities which require to keep track of when the information was provided to a person/company. Think of a return receipt for file downloads.
You end up using stuff like docsend, saleshandy, helprange, and several others. 
When you share a file with a public link and you rename a share in NC, you have all the ingredients. The information is already there, it's difficult to extract. 
My point is it seems to me it'd be a natural extension to the activity app. (eventually with a filter to show just downloads).

BTW, Adding the possibility to specify a provider for a timestamp and digital seal (eIDAS regulation, article 3) would be a boon. It'd become a rock solid valid alternative to all these services for this type of use cases  

I have been envolved in eIDAS from day 1; I firmly believe nextcloud is positioned to become a backbone for legally valid digital transactions in Europe. it'd just require very few features (this one being one of them)
