### ISSUE TITLE
Email Notifications about my own actions not working , share notifications works !

### ISSUE THREAD

**Issue by zemog100** [nextcloud/activity#536]
### Steps to reproduce
1. Activity settings all are check https://ibb.co/Wnkd9w9

2. Cron job works every minute.
3. my own activity is present on Activity ( create file , modify file ...)

- Receive Email test : ok !
- Receive Email change password,: ok !
- Receive Email share file was dowloaded : ok !
- Receive Email day : ok but only share file downloaded.

### Expected behaviour
When i do an action on my files , nothing on database activity_mq  ? ??

### Actual behaviour
can you help me ?

## Server configuration detail

**Operating system:** Linux 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

**PHP version:** 

7.4.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, apcu, igbinary, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, imap, intl, json, ldap, exif, mysqli, pdo_mysql, pdo_pgsql, pgsql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Nextcloud version:** 20.0.3 - 20.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 20.0.2

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - admin_audit: 1.10.0
 - cloud_federation_api: 1.3.0
 - contactsinteraction: 1.1.0
 - dav: 1.16.1
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trackdownloads: 1.9.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - impersonate: 1.7.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - sendent: 1.0.17
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - twofactor_nextcloud_notification: 3.0.0
 - twofactor_totp: 5.0.0
 - updatenotification: 1.10.0
 - user_external: 1.0.0
 - user_status: 1.0.1
 - user_usage_report: 1.4.2
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - calendar
 - comments
 - contacts
 - dashboard
 - encryption
 - files_external
 - firstrunwizard
 - nextcloud_announcements
 - photos
 - twofactor_admin
 - twofactor_gateway
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
 "mydomain",
  "
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "20.0.3.2",
    "overwrite.cli.url": "https:\/\/mydomain\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "remember_login_cookie_lifetime": "1800",
    "log_rotate_size": "10485760",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0.5,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "htaccess.RewriteBase": "\/",
    "maintenance": false,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "knowledgebaseenabled": false,
    "default_language": "fr",
    "default_locale": "fr_FR",
    "trashbin_retention_obligation": "auto, 180",
    "loglevel": "2",
    "theme": "",
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [
        "XXXX"
    ],
    "twofactor_enforced_excluded_groups": [
        "admin"
    ],
    "updater.release.channel": "stable",
    "mail_sendmailmode": "smtp",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** NO

**Are you using encryption: NO ** 

**Are you using an external user-backend, if yes which one:** NO

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Operating system:** UBUNTU 20.04

## Logs

<details><summary>Web server error log</summary>

```
no error on apache2
```
</details>

<details><summary>Nextcloud log</summary>

```
no error log 
```
</details>

<details><summary>SYS log</summary>
Dec 10 16:15:01 nextcloud CRON[71803]: (root) CMD (which zfs-auto-snapshot > /dev/null || exit 0 ; zfs-auto-snapshot --quiet --syslog --label=frequent --keep=4 //)
Dec 10 16:15:01 nextcloud CRON[71809]: (www-data) CMD (php -f /var/www/nextcloud/occ activity:send-mails > /dev/null 2>&1)
Dec 10 16:15:01 nextcloud CRON[71810]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Dec 10 16:15:01 nextcloud CRON[71808]: (www-data) CMD (php -f /var/www/nextcloud/cron.php > /dev/null 2>&1)
Dec 10 16:15:01 nextcloud zed: eid=57 class=history_event pool_guid=0x8096452B6AEF7F26  
Dec 10 16:15:01 nextcloud zfs-auto-snap: @zfs-auto-snap_frequent-2020-12-10-1515, 1 created, 1 destroyed, 0 warnings.
Dec 10 16:15:01 nextcloud zed: eid=58 class=history_event pool_guid=0x8096452B6AEF7F26  
Dec 10 16:15:01 nextcloud zed: eid=59 class=history_event pool_guid=0x8096452B6AEF7F26  
Dec 10 16:16:01 nextcloud CRON[72099]: (www-data) CMD (php -f /var/www/nextcloud/occ activity:send-mails > /dev/null 2>&1)
Dec 10 16:17:01 nextcloud CRON[72220]: (www-data) CMD (php -f /var/www/nextcloud/occ activity:send-mails > /dev/null 2>&1)
Dec 10 16:17:01 nextcloud CRON[72221]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Dec 10 16:17:01 nextcloud zed: eid=60 class=history_event pool_guid=0x8096452B6AEF7F26  
Dec 10 16:17:01 nextcloud zed: eid=61 class=history_event pool_guid=0x8096452B6AEF7F26  
Dec 10 16:17:01 nextcloud zed: eid=62 class=history_event pool_guid=0x8096452B6AEF7F26  
Dec 10 16:17:01 nextcloud zfs-auto-snap: @zfs-auto-snap_hourly-2020-12-10-1517, 1 created, 1 destroyed, 0 warnings.
Dec 10 16:18:01 nextcloud CRON[72477]: (www-data) CMD (php -f /var/www/nextcloud/occ activity:send-mails > /dev/null 2>&1)
Dec 10 16:19:01 nextcloud CRON[72590]: (www-data) CMD (php -f /var/www/nextcloud/occ activity:send-mails > /dev/null 2>&1)
Dec 10 16:20:01 nextcloud CRON[72940]: (www-data) CMD (php -f /var/www/nextcloud/cron.php > /dev/null 2>&1)
Dec 10 16:20:01 nextcloud CRON[72942]: (www-data) CMD (php -f /var/www/nextcloud/occ activity:send-mails > /dev/null 2>&1)
Dec 10 16:21:01 nextcloud CRON[73052]: (www-data) CMD (php -f /var/www/nextcloud/occ activity:send-mails > /dev/null 2>&1)

</details>

**Comment by zemog100** [comment]
Nobody can help me ?

**Comment by enoch85** [comment]
I can confirm this.

Tripple-checked all the settings, tried with AJAX instead of CRON, nothing works. No error logs either from what I could see.

**Comment by eht16** [comment]
To me it seems this feature was removed in https://github.com/nextcloud/activity/pull/565 and https://github.com/nextcloud/activity/pull/572.

What is wondering me, that there seems no ChangeLog entry about the feature removal except the two mentioned PRs.

@nickvergessen @ChristophWurst were self notifications removed and was this intentionally?

**Comment by nickvergessen** [comment]
It was removed as a design decision in #481

**Comment by eht16** [comment]
Thanks for the clarification.
I personally will miss the self notifications but I see your point.

The more important point might be to document this fact somewhere, I spent some hours debugging my instance because the notifications were missing, I didn't find a note in the ChangeLog nor in the net (except very old and therefore unrelated threads in the forum). And the existence of this issue strengthens this.
