### ISSUE TITLE
Add ipaddress to activity reports

### ISSUE THREAD

**Issue by ifuchs** [nextcloud/activity#537]
How to add the ipaddress of the machine that triggers an activity report (e.g. downloads or modifies a file)?

**Comment by ifuchs** [comment]
I would like the Activity app (https://github.com/nextcloud/activity/ 1) to report the ip address of the machine that downloads (or makes other changes) to a file. I believe that the code that would need to be modified is in /var/www/html/apps/activity/lib/MailQueueHandler.php. this information can be obtained using existing logs but it is quite inefficient and would be best if it were (perhaps optionally) available in notifications.

**Comment by szaimen** [comment]
It was decided to not implement this feature because of dsgvo reasons. You can though use this app if you need this feature badly: https://apps.nextcloud.com/apps/files_trackdownloads
