### ISSUE TITLE
PHP Warning: include(): Failed opening

### ISSUE THREAD

**Issue by rigg77** [nextcloud/activity#560]
### Steps to reproduce
1. Deploy Container
2. Navigate to localhost:8080
3. "Finish Setup"

### Expected behaviour
Finish setup 

### Actual behaviour
PHP Warning, check logs statement

### Server configuration

**Operating system:** Raspberry Pi OS Lite / Docker Container

**Web server:** apache

**Database:** alpine-MariaDB

**Nextcloud version:** latest

**Where did you install Nextcloud from:** Docker Hub

### Webserver Log Entry

` 02 14:36:06.485928 2021] [php7:warn] [pid 67] [client x.x.x.x:53342] PHP Warning:  include(): Failed opening '/var/www/html/apps/activity/lib//Migration/Version2011Date20201006132544.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') in /var/www/html/lib/composer/composer/ClassLoader.php on line 476`

Can confirm... `'/var/www/html/apps/activity/lib//Migration/Version2011Date20201006132544.php'` path does not exist; should probably be ...`/lib/Migration/`...

**Comment by edupulpillo** [comment]
Our installation of nextcloud is unuaable since the upcade to Nexcloud version 25.0.4
Warning:  include(): Failed opening '/home/public_html/abacloud/lib/composer/composer/../../../lib/private/Log/ExceptionSerializer.php' 

The error is not present witha fresh instalaltion of 25.0.4

**Comment by nickvergessen** [comment]
That sounds like your upload was canceled and not all files are uploaded.
Please try again and otherwise ask for help in the forums at https://help.nextcloud.com
