### ISSUE TITLE
Activity history is not deleted 'activity_expire_days' => 1,

### ISSUE THREAD

**Issue by witzker** [nextcloud/activity#580]
### Steps to reproduce
1. I put @ the end of the config/config.php
```
 'updater.release.channel' => 'stable',
      'app_install_overwrite' => 
      array (
        0 => 'occweb',
      ),
  'default_phone_region' => 'DE',
  **'activity_expire_days' => 1,**
  );
```
2. wait till cronJob runs = OK
3. No changes in the activity history -  all entries are still there

### Expected behavior
Activity history should be deleted except of last day ('activity_expire_days' => 1,)
### Actual behavior
Tell us what happens instead
No changes in the activity history -  all entries are still there
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
21.0.1
**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.
**List of activated apps:**
occ $ app:list
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - apporder: 0.12.0
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - deck: 1.4.1
  - documentserver_community: 0.1.9
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - groupfolders: 9.0.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - mail: 1.9.5
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - occweb: 0.0.7
  - onlyoffice: 6.3.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.1.2
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - encryption
  - user_ldap
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
If you change the value, the cron job might only do somethign on the next day as it only is executed once a day.
Also when your table is rather big (like multiple gigabytes in #591), the query might run into a timeout. Then you have to execute it once manually directly on the database so there is no connection timeout. There is nothing we can really do about this, as there is no `LIMIT` on delete queries on some databases.

**Comment by witzker** [comment]
Yes THX

the stepps again:
I put @ the end of the config/config.php
```
 'updater.release.channel' => 'stable',
      'app_install_overwrite' => 
      array (
        0 => 'occweb',
      ),
  'default_phone_region' => 'DE',
  **'activity_expire_days' => 1,**
  );
```
wait till cronJob runs = OK
No changes in the activity history - all entries are still there

As you pointed out, The solution above is OK.
The solution to get old entries  deleted is simply  "WAIT" !
 After some days I found old entries gone.

**Comment by enoch85** [comment]
> After some days I found old entries gone.

Yes
