### ISSUE TITLE
"by you" tab doesn't show created or deleted ,files and folders by you

### ISSUE THREAD

**Issue by BabiWD** [nextcloud/activity#582]
Hello I am new to GitHub so if I am not posting this issue or question the right way I sincerely apologize please guide me the right way.
So my problem with Activity app is that in the left menu there is a tab called "by you". I think it should show all of your activities  but it doesn't, it does  editing but it doesn't show created and deleted files!
You might ask why do I need such log, well that's because I use impersonate app to check users activity and it's fine when you are in "all activities" but it's annoying to also see others activities as well and when you switch to "by you" tab it's not showing created/deleted folders and files for some reason and I couldn't find an proper answer online so I thought I should be asking this here if it's a bug or a feature that is for privacy or something that I don't know!
if there is anyone experienced please help me out and thanks.

**Comment by jakobroehrl** [comment]
Maybe similar to: https://github.com/nextcloud/activity/issues/514

**Comment by jakobroehrl** [comment]
I did not see any differences in the table:


MariaDB [nc23]> select * from oc_activity where user='root' and type='file_created' or type='file_deleted' or type='file_changed';
+-------------+------------+----------+--------------+-------+--------------+-------+--------------+--------------------------------------------------------+---------+---------------+----------------------------------+-------------------------------------------------------------------+-------------+-----------+
| activity_id | timestamp  | priority | type         | user  | affecteduser | app   | subject      | subjectparams                                          | message | messageparams | file                             | link                                                              | object_type | object_id |
+-------------+------------+----------+--------------+-------+--------------+-------+--------------+--------------------------------------------------------+---------+---------------+----------------------------------+-------------------------------------------------------------------+-------------+-----------+
|          64 | 1625561540 |       30 | file_created | root  | root         | files | created_self | [{"296":"\/new.md"}]                                   |         | []            | /new.md                          | http://localhost/server23/index.php/apps/files/?dir=/             | files       |       296 |
|          65 | 1625561551 |       30 | file_changed | root  | root         | files | changed_self | [{"296":"\/new.md"}]                                   |         | []            | /new.md                          | http://localhost/server23/index.php/apps/files/?dir=/             | files       |       296 |
|          66 | 1625561571 |       30 | file_deleted | root  | root         | files | deleted_self | [{"178":"\/document.txt"}]                             |         | []            | /document.txt                    | http://localhost/server23/index.php/apps/files/?dir=/             | files       |       178 |
+-------------+------------+----------+--------------+-------+--------------+-------+--------------+--------------------------------------------------------+---------+---------------+----------------------------------+-------------------------------------------------------------------+-------------+-----------+

And I find in the Data.php no special filter or so.

**Comment by jakobroehrl** [comment]
@nickvergessen @artonge 
Could you help me, finding this problem out?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/22205

**Comment by nickvergessen** [comment]
The type is not there as a setting anymore.

I guess we can hack:
https://github.com/nextcloud/activity/blob/fee285e6496e7dde396cab573ab4113920601d87/lib/UserSettings.php#L155-L160
to return the deleted ones as well
