### ISSUE TITLE
Static analysis fails

### ISSUE THREAD

**Issue by artonge** [nextcloud/activity#586]
### Steps to reproduce
Static analysis fails: https://github.com/nextcloud/activity/runs/2546830151?check_suite_focus=true

@ChristophWurst @nickvergessen, an idea why ?

### Expected behaviour
Should not fails.

### Actual behaviour
It fails :wink:

**Comment by nickvergessen** [comment]
The problem is ShareNotFound extends OC\HintException which is not public api.
There is https://github.com/nextcloud/server/pull/26681 to fix it. Until then I guess you have to add it here or something:
https://github.com/nextcloud/activity/blob/master/psalm.xml#L16

**Comment by joshtrichards** [comment]
Fixed long ago.
