### ISSUE TITLE
Allow disabling email notifications for "Your group memberships were modified"

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/activity#626]
A customer would need this, but to me it seems sane to allow this for everybody.

**Comment by marcoambrosini** [comment]
Also cc @LukasReschke to see if this would pose a security hazard

**Comment by LukasReschke** [comment]
Should be fine to disallow. :)

**Comment by marcoambrosini** [comment]
Line in question https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/apps/settings/lib/Activity/GroupSetting.php#L88
