### ISSUE TITLE
disable notification about own activities

### ISSUE THREAD

**Issue by mokkin** [nextcloud/activity#627]
There should be an option for only notifying about other users actions but not your own ones.
I don't like getting notified about stuff I changed one hour ago.

**Comment by danir-de** [comment]
This is really bogging me aswell. When I'm changing stuff in apps like Deck, I'm getting notifications that I changed something two seconds ago.

**Comment by nickvergessen** [comment]
I'm not aware of anything that needs fixing here.
I never get any activity via email nor push that is from my own user. So make sure you update to the latest supported version

**Comment by danir-de** [comment]
@nickvergessen 
I think it's not as bad anymore, but the problem still exists in combination with the deck module.
If you modify a card (add a comment), you'll get notified that you changed the card 2 seconds ago.

**Comment by nickvergessen** [comment]
That is a bug in deck then and not in the activity app.
Mostlikely because of this:
https://github.com/nextcloud/deck/blob/48db9897813000d719fbe7ff8c32c499bfd0113b/lib/Activity/ActivityManager.php#L430-L429
Feel free to report at the deck app and try removing that block
