### ISSUE TITLE
Notifications not working as expected.

### ISSUE THREAD

**Issue by kimberk** [nextcloud/activity#628]
### Steps to reproduce
 Add, edit or remove files or folder from shared/group/favourite folder.

### Expected behaviour
All other shared/group users should be notified by email or push.

### Actual behaviour
Nothing.

### Server configuration

**Operating system: Ubuntu 20.04.2

**Web server: Apache

**Database: default

**PHP version: 7.4.3

**Nextcloud version: 21.0.3 (also tried 21.0.2 - 22.0.0)

**Where did you install Nextcloud from: Hanssonit VM

**Activity App version : 2.14.3 (also tried previous version)

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.

No errors have been found.
```

**List of activated apps:**

Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - apporder: 0.13.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - deck: 1.4.3
  - event_update_notification: 1.3.0
  - extract: 1.3.2
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_accesscontrol: 1.11.0
  - files_antivirus: 3.2.1
  - files_downloadactivity: 1.11.1
  - files_fulltextsearch: 21.0.2
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - flow_notifications: 1.1.0
  - fulltextsearch: 21.0.2
  - fulltextsearch_elasticsearch: 21.0.2
  - group_default_quota: 0.1.2
  - groupfolders: 9.0.2
  - groupquota: 0.1.6
  - integration_whiteboard: 0.0.14
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - notify_push: 0.2.1
  - oauth2: 1.9.0
  - officeonline: 1.1.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - previewgenerator: 3.1.1
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - systemtags: 1.11.0
  - tasks: 0.14.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_ldap: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - announcementcenter
  - encryption
  - files_external
  - firstrunwizard
  - privacy
  - support
  - survey_client

**Nextcloud configuration:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "10.10.51.91",
            "file.mapa.group",
            "file.mapa.group"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "21.0.3.1",
        "overwrite.cli.url": "https:\/\/file.mapa.group\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "upgrade.disable-web": true,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": "7200",
        "log_rotate_size": "0",
        "trashbin_retention_obligation": "auto, 60",
        "versions_retention_obligation": "auto, 180",
        "simpleSignUpLink.shown": false,
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "default_phone_region": "us",
        "logtimezone": "Europe\/Istanbul",
        "htaccess.RewriteBase": "\/",
        "session_lifetime": "7200",
        "share_folder": "\/Shared",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Movie",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF"
        ],
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "26",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable"
    }
}

```
*Activity settings all are check
*Cron job works every minute
*Tried Ajax, no notifications either.
*My own activity is present on Activity
*We can receive email test 
*We can receive email change password
*We can receive email share file was dowloaded
*Push notifications are also only work for updates. There is no notifications for files/folders.

```

**Cron settings:**

0  *  *  *  *    php -f /var/www/nextcloud/occ activity:send-mails
*/5  *  *  *  * php -f /var/www/nextcloud/cron.php > /dev/null 2>&1
*/10 * * * * php -f /var/www/nextcloud/occ preview:pre-generate >> /var/log/nextcloud/previewgenerator.log

```

**Comment by enoch85** [comment]
I can confirm this.

I helped @kimberk to have a look at it, and all settings seems correct. We even tried executing with AJAX, and it didn't produce any activity emails for changed folders/files.

@nickvergessen Any idea here?

**Comment by enoch85** [comment]
This can be closed, explanation is here: https://github.com/nextcloud/activity/issues/536#event-5107565146
