### ISSUE TITLE
Unable to disable mail notification on group membership modifications

### ISSUE THREAD

**Issue by morticah** [nextcloud/activity#631]
Server Version 22.0.0

Checkbox to change notification behavior for 
"Your group memberships were modified" is locked to always send mail for all users.
There is no obvious way for the administrator to change this to never send mail for this event.

I tried occ config:app:set activity notify_email_group_settings --value 0
which changed the checkbox to still locked but unselected.
But this mails for this event are still send.

This is very annoying if you use nextcloud with ldap. You don't want every group change there mailed out to the user.

Am I holding it wrong or is there a bug?

**Comment by ssirio** [comment]
any news about this?
I have the same problem.
Furthermore i have tried to disable all mail notifications without success, the check on "Enable notification emails" is still present despite the password confirmation for the removal.

**Comment by hoangdinhanphabe** [comment]
I tried to enable it but I can't. When I check to the box Enable notifications emails, it forced me to input my password after that nothing happens. And when I refresh the page, that box is empty again. Any ideas I can't set it enable by using occ command ? 
![image](https://user-images.githubusercontent.com/42403971/132633339-952f17d8-1129-4004-9a10-02fa9f5420f9.png)

**Comment by axelos** [comment]
Hello,

> I tried to enable it but I can't. When I check to the box Enable notifications emails, it forced me to input my password after that nothing happens. And when I refresh the page, that box is empty again. Any ideas I can't set it enable by using occ command ?
> ![image](https://user-images.githubusercontent.com/42403971/132633339-952f17d8-1129-4004-9a10-02fa9f5420f9.png)

Même problème rencontré avec Nextcloud 21.0.4.

**Comment by Xeboc** [comment]
It appears the group notification setting is being ignored.  This also affects Nextcloud 22.1.1.2.

One workaround is to delete the notification email from the message queue.  I used this in a bulk user creation script:

```
mysql -p nextcloud -e 'DELETE FROM oc_activity_mq WHERE amq_affecteduser = "<user>";'
```

**Comment by Shyru** [comment]
I also have this issue with LDAP, whats even worse is we have many users that don't even use nextcloud but are in the ldap and they constantly get group notification change emails and don't even use nextcloud. (We are a church and due to COVID we must track every visitor for every service and we add them to a group in the ldap to track that and then the mails get sent out because this tool (ChurchTools) also provides the LDAP for nextcloud.

**Comment by DJeremyy** [comment]
I see what you want to talk about. Users regularly receive emails to inform them that they have been added and removed from a group. Our groups and users are managed with an LDAP.

**Comment by ArmerTropf** [comment]
We have the same problem here. We are having several changes in group memberships as our new identity management software collects group information and creates new groups with new or old members. Any change will result in notification emails. I'm surprised that more users aren't reporting this problem

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/server/pull/28210
So fixed in Nextcloud 23+, 22.1.1+ and 21.0.4+

**Comment by DanScharon** [comment]
@nickvergessen  can't confirm the fix.

We are using Nextcloud 22.2.5.2 and our groups come from LDAP. 
If users didn't change their individual activity settings the instance setting (mail notification about group changes = off) is not respected. Mail notifications are still sent to them about group modifications.

**Comment by nickvergessen** [comment]
> If users didn't change their individual activity settings the instance setting (mail notification about group changes = off) is not respected.

The instance/admin settings are only taken into a account when a new user changes any activity setting for the first time. Afterwards they have the setting set. If you manually delete the user preferences in between it will not fall back to the admin settings, but instead it will take the implementations default which is "true" for email on group changes

**Comment by DanScharon** [comment]
@nickvergessen so if I want to propagate a (new) instance default setting for users that have never set any activity settings themselves I need to add database entries for them?

**Comment by nickvergessen** [comment]
I guess so.

**Comment by DanScharon** [comment]
for anyone interested in how to do that, I did it like this:
```SQL
DO $$
DECLARE
    idtoinsert varchar(64);
BEGIN
FOR idtoinsert IN SELECT DISTINCT userid FROM oc_preferences WHERE appid = 'login'
        AND userid IN (SELECT DISTINCT userid FROM oc_preferences WHERE appid = 'activity')
        AND userid NOT IN (SELECT DISTINCT userid FROM oc_preferences WHERE configkey = 'notify_email_group_settings')
    LOOP
    INSERT INTO oc_preferences (userid, appid, configkey, configvalue)
    VALUES (idtoinsert, 'activity', 'notify_email_group_settings', '0');
    END LOOP;
END$$;
```

**Comment by ZID-TU-Graz** [comment]
Hello, we are experiencing the same issue, Nextcloud Version 22.2.5. 

Now the email notifications are disabled for the current list of users, but if i understand the discussion above, the default setting for email notifications is still not honoring the admin settings. 

In my understanding, https://github.com/nextcloud/server/pull/28210 and the sql statement above do not fix the issue for the users which are provisioned after i run the SQL statement. 

Please tell me if i understand this correctly, if so i would have tu peridocally rerun the sql snippet again.
