### ISSUE TITLE
Two dots in URL "mynextcloud.mydomain..de/core/img/logo/logo.png" (Receiving Calendar activity mail)

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/activity#645]
### Steps to reproduce
1. Create Calendar entry
2. Wait for notification
3.  See missing loaded logo

### Expected behaviour
See logo in Mail

### Actual behaviour
Logo not visible/loadable due to wrong url.

### Server configuration
**Operating system**: Debian 10
**Web server:** Apache
**Database:** SQLite
**PHP version:** 
**Nextcloud version:** 21.0.5

Here are fragments of the received mail:

`<img align="center" alt="MyNextcloud" class="logo float-center" src="https://MyNextcloud.mydomain..de/core/img/logo/logo.png?v=18" style="clear: both;display: block;float: none;margin: 0 auto;outline: 0;text-align: center;text-decoration: none;max-height: 105.0px;max-width: 105.0px;width: auto;height: auto;">`

MyNextcloud.mydomain..de (This ist the problem, a double dot)

Could someone please verify this. I was not able to find the wrong source code.

BTW: config.php is ok, Nextcloud running well. No other URL problems.

Thanks
pm-pm

**Comment by joshtrichards** [comment]
Fixed in nextcloud/server#39607
