### ISSUE TITLE
no notification for favourited files and folders

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/activity#649]
1. Add this setting for User A:
![image](https://user-images.githubusercontent.com/24530680/141096388-6031d4a3-c0ed-43db-997b-9d58b2e231ba.png)
2. create and share a file and a folder with user A
3. favourite this new file and new folder
![image](https://user-images.githubusercontent.com/24530680/141096606-7f80ab6c-36b5-4e9a-9b18-96790b6ed883.png)
4. share the created file and folder with user B
5. login as user B
6. change the file and upload a new file to the folder
7. login as User A, there is no notification:
![image](https://user-images.githubusercontent.com/24530680/141096990-ba4fef47-5feb-4227-bb05-47c98f7ec17f.png)

This function was working, till NC22 (I think)

**Comment by nickvergessen** [comment]
Might be a problem with the translation. The activity option is about the "adding/removing" yellow star action. It't not an item being added in a favorited folder (ref https://github.com/nextcloud/server/pull/28853)

**Comment by paulleentt** [comment]
This seems not a problem with the translation. It does not still work from version 23. 
There is no notification when adding or removing files from "Favorities" folders.

**Comment by nickvergessen** [comment]
> While adding or removing files in favorites,

This is the translation issue.
It's about adding/removing an item from your list of favorited items.
It's not about adding/removing something inside one of your favorited items.
