### ISSUE TITLE
Clarification regarding notifications about my own actions not working

### ISSUE THREAD

**Issue by davralin** [nextcloud/activity#655]
I finally had time to sit down and troubleshoot why I stopped receiving notifications when I did some changes, after searching around - I found the reason for why I no longer receive these messages in #536 and #481.

However digging some more, I also found this #565 - and also [this](https://github.com/nextcloud/server/pull/22205#issuecomment-673477046).

Have I understood it correct that nextcloud/server removed support for this notification to ever happen, and that nothing (reasonable) can be done in activity-app can happen to re-introduce them?

Does anyone know of any hacks or workarounds to re-introduce the functionality, even using third-party software?

**Comment by NextClaus** [comment]
Unfortunately not. I'm also not a coder... I just need this feature back for my users and a don't understand why they removed it o.O
