### ISSUE TITLE
Unable to Enable Notifications Emails 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/activity#662]
Unable to check Enable notifications emails under the Settings> Administrator> Activity I check it and it defaults back to unchcked. Also under Personal > Activity emails notifications are missing only shows Push 

I've tried difference browsers, cleared cache and no luck. 

![image](https://user-images.githubusercontent.com/59488153/135889756-aff49164-3ef9-4d6e-b05b-d3b559b92b63.png)

**Comment by andyxheli** [comment]
Looks like this issue is fixed in NC 23.0.0

**Comment by mthld** [comment]
> Looks like this issue is fixed in NC 23.0.0 @danir-de can you test also

I had this issue too, I confirm it's now working on Nextcloud v23.0.0.

**Comment by artonge** [comment]
Thanks for the feedbacks :)

**Comment by mikulik86** [comment]
Still not working in 22.2.3

**Comment by andyxheli** [comment]
Reopening since this happens on older instances
