### ISSUE TITLE
Activity sidebar tab icon is broken in 23 and master

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/activity#669]
![Bildschirmfoto von 2021-11-26 11-05-17](https://user-images.githubusercontent.com/213943/143563501-296c3f3a-e509-45af-ba5b-c5ae96c15b7b.png)

I guess it's either a regression from https://github.com/nextcloud/nextcloud-vue/pull/1939/ or from #581 with some server changes/updates involved

**Comment by artonge** [comment]
Fixed by updating `@nextcloud/vue` in server.
