### ISSUE TITLE
RSS feed does not work

### ISSUE THREAD

**Issue by hugalafutro** [nextcloud/activity#679]
### Steps to reproduce
1. Go to Activity tab
2. Click the cog in lower left, enable RSS feed
3. Try visiting the provided link

### Expected behaviour
The RSS feed for Activity should appear

### Actual behaviour
404 Not Found page

### Server configuration

**Operating system**:
docker-compose version 1.27.4, build 40524192

**Web server:**
nginx 1.20.2

**Database:**
mysql 10.5.13

**PHP version:**
7.4.26

**Nextcloud version:**
22.2.3

**Where did you install Nextcloud from:**
https://docs.linuxserver.io/images/docker-nextcloud

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.0.4
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.7
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_antivirus: 3.2.2
  - files_external: 1.13.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - files_zip: 1.0.0
  - firstrunwizard: 2.11.0
  - flowupload: 1.1.3
  - imageconverter: 1.3.2
  - integration_google: 1.0.6
  - keeweb: 0.6.8
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.11.5
  - maps: 0.1.10
  - metadata: 0.15.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.2.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - ransomware_protection: 1.12.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.3
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - suspicious_login: 4.1.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather: 1.7.6
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - encryption
  - spreed
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.249:9443",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "has_rebuilt_cache": true,
        "default_phone_region": "UK",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": true,
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "app.mail.verify-tls-peer": false
    }
}
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Vivaldi 5.0.2497.32 (Stable channel) (64-bit)

**Operating system:**
Ubuntu 21.10 5.13.0-22-generic

#### Nextcloud log (data/nextcloud.log)
```
nothing is generated in nextcloud.log when I try to access the rss feed
```

#### Browser log
from nginx access.log
```
192.168.208.1 - - [29/Dec/2021:15:41:14 +0000] "GET /apps/activity/rss.php?token=***REMOVED SENSITIVE VALUE*** HTTP/1.1" 404 185 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.113 Safari/537.36"
```
nothing in nginx error.log

**Comment by acsfer** [comment]
Can't reproduce on my side.

**Comment by sunjam** [comment]
Works fine for me on all versions of Nextcloud up through current 25.0.0

**Comment by AlphaWulfx** [comment]
> ### Steps to reproduce
> 1. Go to Activity tab
> 2. Click the cog in lower left, enable RSS feed
> 3. Try visiting the provided link
> 
> ### Expected behaviour
> The RSS feed for Activity should appear
> 
> ### Actual behaviour
> 404 Not Found page
> 
> ### Server configuration
> **Operating system**: docker-compose version 1.27.4, build 40524192
> 
> **Web server:** nginx 1.20.2
> 
> **Database:** mysql 10.5.13
> 
> **PHP version:** 7.4.26
> 
> **Nextcloud version:** 22.2.3
> 
> **Where did you install Nextcloud from:** https://docs.linuxserver.io/images/docker-nextcloud
> 
> **Signing status:**
> 
> ```
> No errors have been found.
> ```
> 
> **List of activated apps:**
> 
> ```
> Enabled:
>   - accessibility: 1.8.0
>   - activity: 2.15.0
>   - bruteforcesettings: 2.3.0
>   - calendar: 3.0.4
>   - circles: 22.1.1
>   - cloud_federation_api: 1.5.0
>   - comments: 1.12.0
>   - contacts: 4.0.7
>   - contactsinteraction: 1.3.0
>   - dashboard: 7.2.0
>   - dav: 1.19.0
>   - federatedfilesharing: 1.12.0
>   - federation: 1.12.0
>   - files: 1.17.0
>   - files_antivirus: 3.2.2
>   - files_external: 1.13.0
>   - files_pdfviewer: 2.3.1
>   - files_rightclick: 1.1.0
>   - files_sharing: 1.14.0
>   - files_trashbin: 1.12.0
>   - files_versions: 1.15.0
>   - files_videoplayer: 1.11.0
>   - files_zip: 1.0.0
>   - firstrunwizard: 2.11.0
>   - flowupload: 1.1.3
>   - imageconverter: 1.3.2
>   - integration_google: 1.0.6
>   - keeweb: 0.6.8
>   - logreader: 2.7.0
>   - lookup_server_connector: 1.10.0
>   - mail: 1.11.5
>   - maps: 0.1.10
>   - metadata: 0.15.0
>   - nextcloud_announcements: 1.11.0
>   - notes: 4.2.0
>   - notifications: 2.10.1
>   - oauth2: 1.10.0
>   - password_policy: 1.12.0
>   - photos: 1.4.0
>   - privacy: 1.6.0
>   - provisioning_api: 1.12.0
>   - ransomware_protection: 1.12.0
>   - recommendations: 1.1.0
>   - richdocuments: 4.2.3
>   - serverinfo: 1.12.0
>   - settings: 1.4.0
>   - sharebymail: 1.12.0
>   - support: 1.5.0
>   - survey_client: 1.10.0
>   - suspicious_login: 4.1.0
>   - systemtags: 1.12.0
>   - tasks: 0.14.2
>   - text: 3.3.0
>   - theming: 1.13.0
>   - twofactor_backupcodes: 1.11.0
>   - twofactor_totp: 6.2.0
>   - updatenotification: 1.12.0
>   - user_status: 1.2.0
>   - viewer: 1.6.0
>   - weather: 1.7.6
>   - weather_status: 1.2.0
>   - workflowengine: 2.4.0
> Disabled:
>   - admin_audit
>   - encryption
>   - spreed
>   - user_ldap
> ```
> 
> **Nextcloud configuration:**
> 
> ```
> {
>     "system": {
>         "memcache.local": "\\OC\\Memcache\\Redis",
>         "memcache.locking": "\\OC\\Memcache\\Redis",
>         "redis": {
>             "host": "***REMOVED SENSITIVE VALUE***",
>             "port": 6379
>         },
>         "datadirectory": "***REMOVED SENSITIVE VALUE***",
>         "instanceid": "***REMOVED SENSITIVE VALUE***",
>         "passwordsalt": "***REMOVED SENSITIVE VALUE***",
>         "secret": "***REMOVED SENSITIVE VALUE***",
>         "trusted_domains": [
>             "192.168.1.249:9443",
>             "***REMOVED SENSITIVE VALUE***"
>         ],
>         "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
>         "dbtype": "mysql",
>         "version": "22.2.3.0",
>         "dbname": "***REMOVED SENSITIVE VALUE***",
>         "dbhost": "***REMOVED SENSITIVE VALUE***",
>         "dbport": "3306",
>         "dbtableprefix": "oc_",
>         "mysql.utf8mb4": true,
>         "dbuser": "***REMOVED SENSITIVE VALUE***",
>         "dbpassword": "***REMOVED SENSITIVE VALUE***",
>         "installed": true,
>         "mail_from_address": "***REMOVED SENSITIVE VALUE***",
>         "mail_smtpmode": "smtp",
>         "mail_sendmailmode": "smtp",
>         "mail_domain": "***REMOVED SENSITIVE VALUE***",
>         "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
>         "mail_smtpport": "587",
>         "mail_smtpsecure": "tls",
>         "maintenance": false,
>         "theme": "",
>         "loglevel": 2,
>         "has_rebuilt_cache": true,
>         "default_phone_region": "UK",
>         "twofactor_enforced": "true",
>         "twofactor_enforced_groups": [],
>         "twofactor_enforced_excluded_groups": [],
>         "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
>         "mail_smtpauth": 1,
>         "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
>         "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
>         "mail_smtpstreamoptions": {
>             "ssl": {
>                 "allow_self_signed": true,
>                 "verify_peer": false,
>                 "verify_peer_name": false
>             }
>         },
>         "app.mail.verify-tls-peer": false
>     }
> }
> ```
> 
> **Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... no
> 
> ### Client configuration
> **Browser:** Vivaldi 5.0.2497.32 (Stable channel) (64-bit)
> 
> **Operating system:** Ubuntu 21.10 5.13.0-22-generic
> 
> ### Logs
> #### Nextcloud log (data/nextcloud.log)
> ```
> nothing is generated in nextcloud.log when I try to access the rss feed
> ```
> 
> #### Browser log
> from nginx access.log
> 
> ```
> 192.168.208.1 - - [29/Dec/2021:15:41:14 +0000] "GET /apps/activity/rss.php?token=***REMOVED SENSITIVE VALUE*** HTTP/1.1" 404 185 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.113 Safari/537.36"
> ```
> 
> nothing in nginx error.log

When i go to Activity tab and then to Activity setting..nothing happens...cant even see enable RSS feed? Please help
