### ISSUE TITLE
»Error loading activities« placement

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/activity#85]
When there is an error loading the activities in the sidebar, the showNotification has a bit strange placement and stuff looks more broken than it is.
![capture du 2016-12-02 14-43-50](https://cloud.githubusercontent.com/assets/925062/20836315/119d264a-b89f-11e6-8a81-8937cc6f59a7.png)

Instead it should be like the emptycontent comments view:
```
<div class="emptycontent">
  <div class="icon-activity"></div>
  <p>Error while loading activities</p>
</div>
```

cc @nickvergessen

**Comment by nickvergessen** [comment]
What did you do to get that anyway?

**Comment by jancborchardt** [comment]
@nickvergessen good question – it doesn’t appear for new files anymore. But in any case _if_ it appears it should look nice. :)
