### ISSUE TITLE
no activities are showing up with contacts filter

### ISSUE THREAD

**Issue by BitWuehler** [nextcloud/activity#856]
If I look in my activity log to see what contact is created last, I get nothing in the contacts filter. 
![SharedScreenshot](https://user-images.githubusercontent.com/39520752/180842390-b6fae745-f362-4cb1-a317-040417e25fca.jpg)

If I look into "all activities" everything works as espected, also with symbol etc.
![edit](https://user-images.githubusercontent.com/39520752/180842579-6e14ad52-9d7b-4ce2-95be-234482ecfcc3.jpg)

### Server configuration

**Operating system**:
Raspbian GNU/Linux 10 (buster)
5.10.103-v8+ aarch64

**Web server:**
Raspberry Pi 4 4gb
Apache 2.4.25, with HTTP2 enabled

**Database:**
MariaDB 10

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
24.0.2
**Where did you install Nextcloud from:**
docker: ownyourbits/nextcloudpi
Version: v1.48.3

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.

No errors have been found.
```

**List of activated apps:**
Accessibility 1.10.0
Activities for shared file downloads 1.13.0
Activity 2.16.0
Audio Player 3.3.0
Auditing / Logging 1.14.0
Calendar 3.4.2
Circles 24.0.0
Client Push 0.4.0
Collaborative tags 1.14.0
Comments 1.14.0
Contacts 4.2.0
Contacts Interaction 1.5.0
Cookbook 0.9.13
Dashboard 7.4.0
Deleted files 1.14.0
External storage support 1.16.1
Extract 1.3.5
Federation 1.14.0
File sharing 1.16.2
Files automated tagging 1.14.0
First run wizard 2.13.0
GpxPod 4.3.0
Group folders 12.0.1
Impersonate 1.11.0
LDAP user and group backend 1.14.1
Vorgestellt 
Log Reader 2.9.0
Mail 1.13.7
Maps 0.2.0
Monitoring 1.14.0
Nextcloud announcements 1.13.0
Notes 4.4.0
Notifications 2.12.0
Password policy 1.14.0
Passwörter (Version für veraltete Systeme) 2022.6.10
PDF viewer 2.5.0
Photo Sphere Viewer 1.24.0
Photos 1.6.0
Polls 3.7.0
Privacy 1.8.0
Recommendations 1.3.0
Right click 1.3.0
Share by mail 1.14.0
Support 1.7.0
Talk 14.0.3
Tasks 0.14.4
Text 3.5.1
Theming 1.15.0
Two-Factor Authentication via Nextcloud notification 3.4.0
Two-Factor TOTP Provider 6.4.0
Usage survey 1.12.0
User status 1.4.0
Versions 1.17.0
Video player 1.13.0
Weather status 1.4.0

**Nextcloud configuration:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "7": "nextcloudpi",
            "5": "nextcloudpi.local",
            "8": "nextcloudpi.lan",
            "3": "84242d7ed6aa",
            "11": "176.198.79.216",
            "1": "192.168.112.3",
            "14": "84242d7ed6aa",
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.2.1",
        "overwrite.cli.url": "https:\/\/84242d7ed6aa\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/var\/www\/nextcloud\/data\/tmp",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "default_phone_region": "DE",
        "default_language": "de",
        "default_locale": "de"
    }
}
```
### Client configuration
**Browser:** Mozilla Firefox

**Operating system:** Windows 10 21H2

**Comment by skjnldsv** [comment]
> **Nextcloud version:** (see Nextcloud admin page)
> 24.0.2

Seems like we need to fix it for 24 and above @nickvergessen

**Comment by skjnldsv** [comment]
Investigation: The DB filter type is `card` and `addressbook`
![image](https://user-images.githubusercontent.com/14975046/185558056-2388c59a-bba5-48e9-9b84-86fd60bcca6d.png)
![image](https://user-images.githubusercontent.com/14975046/185558381-0847f6ac-ecef-4b5f-a49a-4f94667abf59.png)

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/pull/27061

**Comment by nickvergessen** [comment]
Fix in https://github.com/nextcloud/server/pull/33617

We will also backport it, but it can not fix existing activity entries.
