### ISSUE TITLE
Links created contain "index.php"

### ISSUE THREAD

**Issue by asaage** [nextcloud/activity#892]
Not sure if here is the right place.
I have ```'htaccess.RewriteBase' => '/'``` configured and ```occ maintenance:update:htaccess``` executed.
Everything seems to work as expected and links are generally generated without ```index.php``` in the url except in the activity-app.
Once such url is clicked the ```index.php``` appears for every following link on other pages (meaning everything is actualy reachable with and without pretty-urls)
That does not seem to be right - maybe someone experienced the same and can give some advice?

### Server configuration
**Operating system**: ubuntu
**Web server:** apache behind nginx reverseproxy (plesk)
**PHP version:** 8.1
**Nextcloud version:** 24.0.4

**Comment by nickvergessen** [comment]
Which activities have the wrong links?
Please not that the activity app is only an empty skeleton and each app is responsible for translating the message, adding previews and providing links.

**Comment by asaage** [comment]
> Which activities have the wrong links?

Basically every filename/icon/thumbnail that has been changed/created/deleted as well as card and board names.

**Comment by asaage** [comment]
Turns out to be a plesk-thing...
If i configure my php-settings to be "FPM application served by Apache" all that does not happen.
Earlier i had "FPM application served by nginx" (maybe hoping for better performance).

**Comment by nickvergessen** [comment]
Thanks for letting us know.
