### ISSUE TITLE
Conflicting HTML ID attribute after update (+EMail Notification change)

### ISSUE THREAD

**Issue by EngelPika32** [nextcloud/activity#897]
Related issue for notifications-app: https://github.com/nextcloud/notifications/issues/1259#issue-1354550317

- - - - -

The select entries of these two share the same ID `notify_setting_batchtime`. 
![2022-08-29_17-31](https://user-images.githubusercontent.com/41995155/187238361-a73db562-81cb-4aed-bfdb-fb09131fd9c5.png)
*(I removed some table entries to fit top&bottom in one screenshot)*
![2022-08-29_17-36](https://user-images.githubusercontent.com/41995155/187239043-3f05901a-7107-4e98-acde-258235ae72f0.png)

PR adding the new option: https://github.com/nextcloud/notifications/pull/1074
File (in notifications): `src/views/UserSettings.vue:30`
File (in activity): `templates/settings/form.php:73`

One of these has to change their ID.

I noticed #861 making a lot of changes, so, the HTML-ID issue might be fixed already?

### Steps to reproduce

Updated from NC22 *(latest patch)* to NC23 *(latest patch)*.

Since that update an additional option appeared under `settings/user/notifications`. [The top one from the images.]
(Caused by the notification app.)

### Expected behaviour
No un-asked e-mail notification. 
I dunno what these "unhandled notifications" are, but I never asked to receive E-Mails for stuff I've selected "push" for. 

Additionally, I don't see any admin option about this to set defaults.
(Caused by the notification app.)

### Actual behaviour
Un-asked e-mail notification from (apparently) a new option. 

The HTML code includes ID conflicts (more than one element with the same ID).

### Server configuration

**Operating system**: Arch Linux

**Web server:** caddy

**Database:** MariaDB

**PHP version:** 8.0

**Nextcloud version:** (see Nextcloud admin page) 23.0.8

**Where did you install Nextcloud from:** Docker (fpm)

**Signing status:** `No errors have been found.`

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
- - - - -

**Comment by nickvergessen** [comment]
Master fixed with https://github.com/nextcloud/activity/pull/900

As mentioned in the notification ticket older branches will be fixed on the notification app since it's easier there.
