### ISSUE TITLE
Add UserAgent information to activities

### ISSUE THREAD

**Issue by Offerel** [nextcloud/activity#98]
It would be great, if i could have the Info, from which UserAgent a Action was performed and maybe a IP Address. But IP Address is not so important for me. Background Info: Currently i use Activity App to have an eye which Calendar Entry was changed and which Client does change the Calendar or a Event in the Calendar. Sometimes i have more than one Client Application on a Device, so that it is difficult to see, which client have made a change. For Instance, i have found that eM Client 7 has deleted all Events in one Calendar. I don't know why but i takes a long time to found out, that eM Client was the Problem and not other Client.

**Comment by nickvergessen** [comment]
This will cause a lot of work, but if someone implements this I'd say why not.

The main question is on which level it should be handled. Should it be part of the event (so explicitly stored by the activity app) or part of the content (apps can already do that now)

**Comment by Offerel** [comment]
Hmm im not clear what the two Options mean for me as a Enduser. But as the Enduser i think that every change on a Calendar Event, specially a Delete of Single Event, a change or Delete in Event Series Exception and the Mass deletion of Events or the whole calendar should be traceable with the Information of the UserAgent. 

Lets assume the following Situation: You have the NextCloud Server on your HomeServer. This HomeServer is reachable by a DynDNS Address. You use this DynDNS Address also on all your Clients in your Homenetwork. In Your Homenetwork you have 3 PC's using this Calendar and 5 Smartphones or Tablets. All of them use the DynDNS Address. From Server View, all have the same IP Address, but since they use different Apps, every App has it's own UserAgent. If now App XYZ freaks out and deletes some Events, you can see which App has done this crazy thing via the Activitys App or the Server Logfiles.  So far my thoughts about this. I don't know if this is already possible, i haven't found something which i could use in the Logs. If you know a better or easier way accept the Activity App, please let me know.

**Comment by nickvergessen** [comment]
Well the server's log file should already be able tell you that. It looks the request and the ip+user agent. But yeah that's more for server admins not for real end-users.

**Comment by nickvergessen** [comment]
We can not save the IP address due to the european data protection law: GDPR

**Comment by dusscloud** [comment]
> 
> 
> We can not save the IP address due to the european data protection law: GDPR

IP address is indeed a personal data, thus to be handled through GDPR.

But GDPR does not say you cannot save personal data. 
As any other personal data, it means you need to either propose this as optional to the end user (opt out by default), or explicitly write it is saved and explain why this is mandatory for the use of the service. 
In the case of a public link sharing, I think it can this personal data can be seen as a required field for security purpose (avoid non solicited download for instance).
